CI 스크립트 개선
woowacourse-teams/2024-devel-up pull request #111
Opened 2024-07-23 08:16 UTC by lilychoibb

#### 구현 요약

- 프론트/백엔드 ci 스크립트 분리
- ci 트리거 labels > path 로 변경
- permissions 제거
- gradle caching
- gradle build > test 로 변경

#### 연관 이슈

close #108 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-07-23 14:23 UTC, le2sky commented
지나가다 들려요. 
gradle 캐싱을 적용했을 때 CI 과정의 성능 개선이 얼마나 이루어졌는지 측정해보는 건 어떨까요?

2024-07-24 01:44 UTC, lilychoibb commented
> 지나가다 들려요. gradle 캐싱을 적용했을 때 CI 과정의 성능 개선이 얼마나 이루어졌는지 측정해보는 건 어떨까요?

오 좋네요 ㅎㅎ 측정해보고 결과 붙여서 pr 업데이트 해놓겠습니다

2024-07-24 02:27 UTC, lilychoibb commented
<img width="1062" alt="ci_개선전" src="https://github.com/user-attachments/assets/56cfa683-667d-4d14-b980-a374fbe4dfd5">
> 개선 전
<img width="1064" alt="ci_개선후" src="https://github.com/user-attachments/assets/d757e191-84eb-4c41-8eaf-87adfd1362cd">
> 개선 후


gradle caching 적용 전 후 Total duration 기준으로 16s, 슬랙 메시지 전송을 제외한 BE_CI 기준으로 19s 속도 개선되었습니다 :)

2024-07-24 04:20 UTC, Minjoo522 requested changes
안녕하세요, 릴리!
짧은 시간 안에 스크립트 개선하느라 고생했습니다. 👍
몇 가지 코멘트 달아 두었으니 확인 부탁드려요!

2024-07-24 04:20 UTC, Minjoo522 commented on .github/workflows/backend_ci.yml
> +        run: chmod +x ./backend/gradlew
[Comment]

[setup-gradle@v3](https://github.com/gradle/actions/blob/main/docs/setup-gradle.md)를 사용하면 보다 간편하고 효율적으로 캐싱 할 수 있다고 합니다! 😊

[GitHub Actions 공식 문서](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle#caching-dependencies)에서도 확인할 수 있습니다.

2024-07-24 04:20 UTC, Minjoo522 commented on .github/workflows/backend_ci.yml
> +            return mention.join(', ');
[Approve]

현재 팀 멤버는 변경될 가능성이 굉장히 적은데 차라리 상단에 env나 상수로 정의하는 건 어떨까요?

2024-07-24 04:20 UTC, Minjoo522 commented on .github/workflows/backend_ci.yml
> +          settings-path: ${{ github.workspace }} # location for the settings.xml file
[Comment]

이 부분은 Maven 빌드할 때 사용되는 부분인 것으로 알고 있습니다!

2024-07-24 05:32 UTC, lilychoibb commented on .github/workflows/backend_ci.yml
> +            return mention.join(', ');
json 을 따로 분리해두어 사용하는 방식은 파일에 접근하고 추가적인 I/O 를 위한 작업을 해야하긴 하지만 데이터와 로직을 분리해둔다는 장점이 있는 것 같아요!
리브가 제안주신 스크립트 하나에서 처리하는 방식은 한 곳에서 관리할 수 있다는 장점이 있지만 env 로 정의하더라도 readFileSync 만 수행하지 않을 뿐 json parse 를 해야하고, 상수는 스크립트 내에 정의해두면 스크립트가 너무 길어질 것 같아요.

말씀주신 것과 다른 내용이긴 하지만 위의 스크립트가 지금도 충분히 길어서 계속 개선점을 찾고 있는데,, 아직은 쉽지 않네요 🥹

2024-07-24 05:33 UTC, lilychoibb commented on .github/workflows/backend_ci.yml
> +        run: chmod +x ./backend/gradlew
수동으로 작업해주지 않아도 되었군요 👍 반영해놓겠습니다~

2024-07-24 07:36 UTC, lilychoibb commented on .github/workflows/backend_ci.yml
> +            return mention.join(', ');
assignee -> sender 로 변경 후 수정

2024-07-24 08:37 UTC, merged