BE CD yml 파일 리팩토링 (issue #107)
woowacourse-teams/2024-devel-up pull request #113
Opened 2024-07-23 12:37 UTC by Minjoo522

#### 구현 요약

BE CD 깃허브 리소스 사용하도록 개선합니다.

#### 연관 이슈

close #107 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-07-23 14:19 UTC, le2sky requested changes
리브 안녕하세요. 아톰입니다.  
엄청 빠르게 구현해주셨네요. 👍
사소한 커멘트 하나 남겼어요. 시간 나실 때, 확인 부탁드립니다.

2024-07-23 14:19 UTC, le2sky commented on .github/workflows/cd.yml
> +          mv ${{ env.ARTIFACT_DIRECTORY }}/*.jar ${{ env.ARTIFACT_DIRECTORY }}/${{ env.ARTIFACT_NAME }}.jar
[Comment] 

빌드 아티팩트를 이동시키면서 이름도 변경하는 것으로 보이는데 맞을까요?
개인적으로 이름은 build.gradle에서 관리되는 것을 선호합니다.
build.gradle 내부에 version을 변경하여 여러 버전별 빌드 아티팩트를 관리해볼 수 있을 것 같아요.
제가 놓치고 있는 부분이 있다면 부연 설명 부탁드립니다. 🙇🏻‍♂️

2024-07-23 14:24 UTC, le2sky commented on .github/workflows/cd.yml
> +          mv ${{ env.ARTIFACT_DIRECTORY }}/*.jar ${{ env.ARTIFACT_DIRECTORY }}/${{ env.ARTIFACT_NAME }}.jar
++ 추가로 아래 ci 개선 PR에서는 gradle 캐싱이 적용되어 있는 걸로 보이는데요. cd 과정에서는 불필요할까요?

2024-07-23 14:44 UTC, robinjoon requested changes
안녕하세요 리브! 역시 리브 그 사이에 금방 공부해서 기존 스크립트를 개선하는 것 보니 듬직하네요!! ㅎㅎ

제가 봤을 때, 이번에 변경한 사항은 크게 3가지라고 생각해요. **이 외에도 작업한 주요 사항이 있다면 제가 적은 항목들과 함께 잘 정리해서 이슈에 적어주시면 좋을 것 같아요!** 

1. 기존에 step 단위로 빌드와 배포가 구분 => Job 단위로 빌드와 배포가 구분
2. 빌드도 self-hosted runner 위에서 동작함 => 빌드는 깃허브가 제공하는 runner 에서 동작함
3. 그레이들 캐시를 적용함

첫번째 항목의 경우에는 작업 흐름의 가시성 측면에서는 확실히 좋아진 것 같아요. 
![image](https://github.com/user-attachments/assets/d4678fb3-ca42-41ca-84a7-cf5ed78c5421)

두번째 항목 역시 단순히 생각했을 경우 웹 서버이기도 한 self-hosted runner 의 작업 부하가 줄어들어서 좋을 것 같아요. 하지만, 구체적으로 얼마나 부하가 줄어들었는지를 알 수 있다면 보다 더 탄탄한 개선 작업을 한 이유가 될 수 있을 것 같아요! 

또한, Job 단위로 구분하면서 아티팩트를 사용하게 되고 러너들 사이에 빌드 파일을 네트워크로 주고 받는 것 같아요. 반면, 기존 방식 대로 self-hosted 러너에서 스텝 단위로 구분한다면 이런 네트워크 통신이 사라져서 조금 더 빠를 수 있을 것 같아요. **두 경우의 속도 차이가 측정이 가능하다면, 측정해보는 것도 좋을 것 같아요!**

세번째 항목도 캐시를 추가해서 얼마나 성능 향상이 있었는지 측정해 보는 것도 좋을 것 같아요!

리뷰를 남기고 보니까, 약간 억까하는(?) 느낌을 받을 수도 있을 것 같아요. 하지만, 지금 백엔드 CI / CD 작업은 우선 동작하도록 완료된 것 같고, 아직 시간이 있다고 생각해서 정량적 지표를 도출하는 것도 좋을 것 같다고 생각되서 RC 를 남겼어요.

2024-07-23 15:32 UTC, Minjoo522 commented on .github/workflows/cd.yml
> +          mv ${{ env.ARTIFACT_DIRECTORY }}/*.jar ${{ env.ARTIFACT_DIRECTORY }}/${{ env.ARTIFACT_NAME }}.jar
`1`
이름을 변경하면 다운로드 받을 때 편하게 받을 수 있을거라고 생각했는데, 사실 변경하지 않아도 괜찮았었네요 😅
아톰의 `build.gradle`에서 관리하자는 의견에 완전 동의해서 반영했습니다! 👍

`2`
[참고 문서](https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#caching-build-state-between-jobs)
`gradle/actions/setup-gradle@v3` 라이브러리의 기본 값이 캐싱이라서 따로 설정해 줄 필요가 없었습니다! 👍

![image](https://github.com/user-attachments/assets/2b369fc7-9b35-4cb2-a3d9-db0c4169e60c)

2024-07-24 01:00 UTC, alstn113 approved these changes
와우 엄청난 성장 속도네요! 배포 든든합니다. 👍👍

2024-07-24 04:38 UTC, le2sky approved these changes
확인했어요. 고생 많으셨습니다. 👍

2024-07-24 04:49 UTC, robinjoon approved these changes

2024-07-24 05:57 UTC, lilychoibb approved these changes
짧은 시간 안에 고생 많으셨어요!
다른 분들이 충분히 의견 남겨주신 것 같아서, 바로 Approve 하겠습니다 :)

2024-07-24 05:59 UTC, merged