인가 코드 작성
woowacourse-teams/2024-devel-up pull request #127
Opened 2024-07-24 06:45 UTC by alstn113

#### 구현 요약

깃허브 인가 코드를 작성했어요.

#### 연관 이슈

close #99 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-07-24 14:03 UTC, le2sky requested changes
구름 안녕하세요. 아톰입니다.
항상 좋은 코드 작성해주셔서 감사합니다.
몇 가지 궁금한 사항이랑 피드백 남겨놨어요. 
시간 괜찮으실 때, 확인 부탁 드립니다. 👍

2024-07-24 14:03 UTC, le2sky commented on backend/src/test/java/develup/infra/auth/JwtTokenProviderTest.java
> +
[Request Changes]

개행 두개 발견 👀

2024-07-24 14:04 UTC, le2sky commented
++ 개선 라벨은 실수로 등록하신건지 궁금해요.

2024-07-24 14:07 UTC, alstn113 commented on backend/src/test/java/develup/application/member/MemberServiceTest.java
> +                .hasMessage(ExceptionType.MEMBER_NOT_FOUND.getMessage());
열심히 말하고 회의한다고 까먹었네요 ㅎㅎ 수정하겠습니다 ⛅️

2024-07-24 14:11 UTC, alstn113 commented on backend/src/main/java/develup/application/auth/Accessor.java
> +    public static final Long GUEST_ID = -1L;
상수로 빼다가 잘못 적었나보네요. 수정했습니다. ⛅️

2024-07-24 14:13 UTC, alstn113 commented on backend/src/main/java/develup/infra/auth/oauth/github/GithubOAuthProperties.java
> +package develup.infra.auth.oauth.github;
아시겠지만 소셜로그인이라서 oauth를 붙였어요. 
깃허브밖에 없기도 하고 패키지 명도 길어지니 auth.github로 변경할게요 🌧️

2024-07-24 15:03 UTC, alstn113 commented on backend/src/main/java/develup/application/auth/AuthorizationExtractor.java
> +}
인터페이스는 Cookie나 Bearer로 변경될 가능성이 높기도 하고,
default T extract(NativeWebRequest request) <- 이 부분을 가리고 싶었어요.

응용 계층에 들어간 이유는 습관처럼 넣었는데 잘못 넣은 것 같아요.
HttpServletRequest, NativeWebRequest가 있으니 presentation에 위치하는게 맞을 것 같아요.

` - 30분 공백 - `

인터페이스: presentation, 구현체: infra 등등 여기저기 옮겨보다가, 그냥 인터페이스 날렸습니다.

2024-07-24 15:50 UTC, alstn113 commented
[refactor: CookieUtils 분리 및 인증 실패 시 쿠키 제거](https://github.com/woowacourse-teams/2024-devel-up/pull/127/commits/95251b9ce7863ab54df8afe598878e77eab6d644)

AuthArgumentResolver의 handleToken 부분은 'token'이라는 쿠키가 있고, 유효하지 않거나, 존재하지 않는 멤버일 경우 예외가 발생합니다.
이 경우 사용자가 문제를 해결할려면 직접 쿠키를 지워야합니다. 그런 수고를 덜기 위해서 예외가 발생할 경우 쿠키를 지울 수 있게 했습니다.
이 과정에서 AuthApi의 Cookie 메서드들을 CookieUItils로 분리했습니다.

2024-07-24 23:50 UTC, le2sky commented on backend/src/main/java/develup/application/auth/AuthorizationExtractor.java
> +}
👍👍 굳굳 참고에 남겨주신 부분도 좋아요.

2024-07-24 23:55 UTC, le2sky approved these changes
늦은 시간까지 고생 많으셨습니다! 👍👍

2024-07-25 00:51 UTC, robinjoon approved these changes

2024-07-25 01:19 UTC, merged