제출 단건 조회 기능 구현(issue #211)
woowacourse-teams/2024-devel-up pull request #223
Opened 2024-08-07 13:32 UTC by le2sky

#### 구현 요약

제출 단건 조회 기능을 구현했습니다.

#### 연관 이슈

- close #211 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-08-07 13:33 UTC, le2sky commented on backend/src/test/java/develup/domain/mission/MissionTest.java
> +        assertThat(actual).isEqualTo(expected);
이 부분 actual과 expected 바뀐것으로 판단하여 수정했습니다. 
의도된 부분이라면 말씀 주세요.

2024-08-07 13:34 UTC, le2sky commented on backend/src/test/java/develup/api/MissionApiTest.java
> +        Mission mission = MissionTestData.defaultMission().withId(1L).build();
이 부분 save할 필요가 없다고 생각하여, 테스트 데이터 빌더의 withId를 사용하도록 변경했어요. 문제되는 부분이 있다면 편하게 말씀 주세요. 😀

2024-08-07 14:29 UTC, alstn113 requested changes
수고하셨습니다. 👍👍👍👍👍👍👍

![image](https://github.com/user-attachments/assets/92e94d2d-3fe3-494a-97c3-aaf5c382bf4c)

2024-08-07 14:29 UTC, alstn113 commented on backend/src/main/java/develup/api/SolutionApi.java
> +public class SolutionApi {
[Request Changes]

```suggestion
@RestController
@Tag(name = "솔루션 API")
public class SolutionApi {
```

2024-08-07 14:29 UTC, alstn113 commented on backend/src/test/java/develup/api/SolutionApiTest.java
> +                .andExpect(jsonPath("$.data.length()", is(2)));
[Approve]

`$.data[0].id`, `$.data[1].id`는 일부러 안넣으신걸까요?

2024-08-07 14:29 UTC, alstn113 commented on backend/src/test/java/develup/api/SolutionApiTest.java
> +        BDDMockito.given(solutionService.getById(any()))
[Approve]

anyLong()이 아니라 any()로 넣어도 잘되나 보네요

2024-08-07 14:29 UTC, alstn113 commented on backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
> +    }
[Approve]

예전에 식별자라는 단어를 쓰자고 했던 것 같아서 "미션 ID -> 미션 식별자"는 어떨까요?
expected가 너무 많아서 잘 안읽히더라구요.
마지막에 바꾼  assertAll은 어색하긴하네요. 

```suggestion
    @Test
    @DisplayName("멤버 식별자와 미션 식별자와 특정 상태에 해당하는 솔루션이 존재하는지 확인한다. ")
    void exists() {
        Member member = memberRepository.save(MemberTestData.defaultMember().build());
        Mission mission = missionRepository.save(MissionTestData.defaultMission().build());
        SolutionStatus inProgress = SolutionStatus.IN_PROGRESS;
        SolutionStatus completed = SolutionStatus.COMPLETED;
        Solution inProgressSolution = SolutionTestData.defaultSolution()
                .withMember(member)
                .withMission(mission)
                .withStatus(inProgress)
                .build();
        solutionRepository.save(inProgressSolution);

        boolean exists = solutionRepository.existsByMember_IdAndMission_IdAndStatus(
                member.getId(),
                mission.getId(),
                inProgress
        );

        boolean notExists = solutionRepository.existsByMember_IdAndMission_IdAndStatus(
                member.getId(),
                mission.getId(),
                completed
        );

        assertAll(
                () -> assertThat(exists).isTrue(),
                () -> assertThat(notExists).isFalse()
        );
    }
```

2024-08-07 14:29 UTC, alstn113 commented on backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
> +    }
[Commnet]

솔루션을 12개나 저장해서 테스트하는건 과한 것 같아요.

2024-08-07 14:29 UTC, alstn113 commented on backend/src/test/java/develup/api/MissionApiTest.java
> +        Mission mission = MissionTestData.defaultMission().withId(1L).build();
[Approve]

좋은 것 같아요.
이 부분이 로그인 여부, 미션 진행 여부에 따라 달라지는데 mock이라 테스트가 의미가 없더라구요.
그래서 "미션을 조회한다." 이것만 했습니다. 참고해주세요.

2024-08-07 23:00 UTC, le2sky commented on backend/src/test/java/develup/api/SolutionApiTest.java
> +        BDDMockito.given(solutionService.getById(any()))
네 맞아요. 차라리 anyLong이 나을까요?

2024-08-07 23:02 UTC, le2sky commented on backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
> +    }
반영했습니다! 제안주셔서 감사해요. 👍
마지막 부분 정도는 괜찮다고 생각했어요.

2024-08-07 23:06 UTC, le2sky commented on backend/src/test/java/develup/api/SolutionApiTest.java
> +                .andExpect(jsonPath("$.data.length()", is(2)));
감사합니다. 제가 놓친 부분이네요. 😂

2024-08-07 23:07 UTC, le2sky commented on backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
> +    }
2개로도 충분히 검증 가능하다 판단하여, 2개로 바꾸고 반복 저장 메서드도 지우도록 변경했어요.
어색한 부분이 있다면 추가 피드백 부탁드립니다.

2024-08-08 02:14 UTC, Minjoo522 approved these changes
안녕하세요 아톰!
대부분 말로 얘기 한 것 같아서 소소한 코멘트 남겼습니다! 고생했습니다!

2024-08-08 02:14 UTC, Minjoo522 commented on backend/src/main/java/develup/api/SolutionApi.java
> +        List<SolutionSummary> summaries = solutionRepository.findCompletedSummaries();
[Comment]
이 로직을 Service로 빼서 SolutionApi에서 Respository에 대한 의존성을 뺄 수 없을까요?

2024-08-08 02:14 UTC, Minjoo522 commented on backend/src/test/java/develup/api/SolutionApiTest.java
> +        BDDMockito.given(solutionService.getById(any()))
[Approve]

any()나 anyLong() 어떤 걸 쓸지 하나로 같이 통일할 수 있도록 논의를 해보면 좋을 것 같습니다!

2024-08-08 02:17 UTC, lilychoibb approved these changes
굿 ⍢ 👍

2024-08-08 02:18 UTC, alstn113 approved these changes

2024-08-08 02:21 UTC, merged