미션 제출 기능 리팩터링 (issue #266)
woowacourse-teams/2024-devel-up pull request #267
Opened 2024-08-10 07:09 UTC by lilychoibb

#### 구현 요약

미션 제출 기능에 대한 리팩터링을 진행했습니다.

#### 연관 이슈

- close #266 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-08-10 07:30 UTC, robinjoon approved these changes
안녕하세요 릴리! 대부분의 작업이 다 같이 진행한 내용이라 작업 자체에 대해서는 추가로 남길 코멘트가 거의 없네요. 다만, 이번 작업에서 리팩토링한 것이 무엇인지 이슈에서도, PR 에서도 한눈에 확인할 수가 없네요.

제가 기억나는 작업 내용은 아래 정도로 기억해요. 추가로 한 작업이 있다면 이슈나 PR에 설명을 추가해주면 좋을 것 같아요!
- DTO에 Spring Validation 적용
- 레퍼지토리가 Optional을 반환
- 일부 누락된 테스트 코드 추가

2024-08-11 01:50 UTC, alstn113 requested changes
주말에도 파이팅하셨습니다!!! ⛅️⛅️ 👍👍👍👍👍👍👍👍

자잘한 것들 리뷰 남겼습니다. 
저번에 MissionRepositoryName에 대해서 변경하기로 하지 않았나요?
다시 한 번 확인 부탁드립니다!

2024-08-11 01:50 UTC, alstn113 commented on backend/src/main/java/develup/api/StartSolutionRequest.java
[Comment]

startMission api에서 request.missionId()를 서비스로 내려주더라구요.
dto값이 추가되는 경우가 있을 수도 있고, 다른 dto들의 위치와 일관성을 위해서 service로 dto를 넘기는 것은 어떨까요?
만약 넘긴다면 이 dto의 위치도 api/에서 application/으로 이동해야할 것 같아요.

2024-08-11 01:50 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/SolutionRequest.java
[Comment]

StartSolutionRequest를 먼저 읽고와서 그런지 모르겠는데
SolutionRequest를 읽었을 때 이게 뭐였지라는 생각이 들더라구요. 
SubmitSolutionRequest로 변경하면 어떨까요?

2024-08-11 01:50 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/SolutionResponse.java
> +                solution.getTitle().getValue(),
[Comment]

이 부분이 보여서 든 생각인데 Solution Entity에서 getTitle을 할 때 반환값을 Title로 하는게 아닌 String으로 하는건 어떨까요?

2024-08-11 01:50 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/Solution.java
[Request Changes]

column에 nullable false를 붙여주세요

2024-08-11 01:50 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/Title.java
> +    }
[Request Changes]

리플렉션 때문에 쓰는거라 내용물 필요 없을 것 같아요.

```suggestion
    protected Title() {
    }
```

2024-08-11 01:50 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/Title.java
> +    }
[Approve]

구체적으로 적으면 좋을 것 같아요

```suggestion
    private void validateIsNotBlank(String value) {
        if (value.isBlank()) {
            throw new DevelupException(ExceptionType.INVALID_TITLE);
        }
    }
```

2024-08-11 03:23 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/Solution.java
[Request Changes]

description 컬럼이 255자 넘을 것으로 예상돼요.
columnDefinition = TEXT로 변경해주세요

2024-08-11 09:31 UTC, le2sky approved these changes
릴쌤! 사소한 커멘트 하나 남겼는데요. 
선택적으로 반영해주셔도 좋을 것 같아요. 고생 많으셨습니다. 👍

2024-08-11 09:31 UTC, le2sky commented on backend/src/main/java/develup/application/solution/SolutionRequest.java
[Approve] 

위에 구름이 남겨주신 의견 좋다고 생각해요. 
한 단계 더 나아가서 SubmitSolutionRequest 내부에 SolutionSubmit 생성 책임을 주는 것을 어떨까요?
그리고 SolutionSubmit 자체에 solutionService.validatePullRequestUrl 를 위임할 수 있을 것 같아요.

```java
public SolutionResponse submit(Long memberId, SubmitSolutionRequest submitSolutionRequest) {
        Solution solution = solutionRepository.findByMember_IdAndMission_IdAndStatus(
                        memberId,
                        solutionRequest.missionId(),
                        SolutionStatus.IN_PROGRESS
                )
                .orElseThrow(() -> new DevelupException(ExceptionType.SOLUTION_NOT_STARTED));
        SolutionSubmit solutionSubmit = submitSolutionRequest.toSubmitPayload();

        solution.submit(solutionSubmit);

        return SolutionResponse.from(solution);
    }
```

PR이 루즈해질 수도 있으니, 릴쌤의 선호에 따라 선택적으로 반영해주세요.

2024-08-12 02:28 UTC, Minjoo522 approved these changes
릴리 주말에 고생많았습니다!
필요한 코멘트 대부분 구름이 남겨주어 간단한 첨언(?)만 드립니다.

2024-08-12 02:28 UTC, Minjoo522 commented on backend/src/main/java/develup/application/solution/SolutionResponse.java
> +                solution.getTitle().getValue(),
구름의 의견에 덧붙이자면 이전에 get 여러개 붙이지 않기 위해 상위 객체에서 원시값을 꺼내주자는 의견이 더 많았던 것으로 기억합니다!

2024-08-12 08:47 UTC, lilychoibb commented
여러분이 남겨주신 리뷰 모두 공감되는 내용이라 거의 다 반영했어요!
다만 SolutionService 의 validatePullRequestUrl 에서 missionRepositoryName 을 검증하는 방식이 변경됨에 따라서, 검증 로직을 SolutionSubmit 에 위임해도 괜찮을 것 같다는 의견은 반영하지 않았어요.
추가 의견이 있다면 편하게 말씀 부탁드려요 😀

2024-08-12 08:49 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/SolutionSubmit.java
> +    }
[Request Changes]

domain 패키지에서 application 패키지의 SubmitSolutionRequest를 사용하네요.
방향이 반대가 되면 좋을 것 같아요.

2024-08-12 08:54 UTC, le2sky commented on backend/src/main/java/develup/domain/solution/SolutionSubmit.java
> +    }
submitSolutionRequest.toSubmitPayload를 의도했었어요!
이 부분만 반영해주시면 좋을 것 같아용

2024-08-12 08:56 UTC, lilychoibb commented on backend/src/main/java/develup/domain/solution/SolutionSubmit.java
> +    }
아하 ㅋㅋㅋㅋㅋㅋㅋ 뭔가 이게 맞나 하면서 구현했는데 역시 아니였군요 ㅋㅋㅋㅋㅋ ㅠㅠ 반영해놓을게요!

2024-08-12 14:58 UTC, robinjoon approved these changes

2024-08-12 14:58 UTC, robinjoon commented on backend/src/main/java/develup/domain/solution/Title.java
> +public class Title {
[질문] 제가 한동안 인프라나 다른 부분을 담당하다가 와서 헷갈려서 질문드립니다!  왜 일반 클래스로 변경한 건가요? **우리 프로젝트에서 record를 사용하는 규칙**이 따로 있나요?

혹시 오해하실까봐 record를 사용해야 한다는 취지로 남기는 말이 아니에요!

2024-08-12 16:04 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/Title.java
> +public class Title {
@robinjoon 

제가 record 말고 class로 바꿔달라고 했어요.
이유는 그 때 말 안했지만 다른 것들과 일관성을 위해서 입니다. ⛅️

2024-08-13 01:15 UTC, alstn113 approved these changes

2024-08-13 01:40 UTC, merged