@WebMvcTest로 전환(issue #270)
woowacourse-teams/2024-devel-up pull request #271
Opened 2024-08-11 12:51 UTC by le2sky

#### 구현 요약

기존 api 테스트를 @WebMvcTest로 전환했어요.
추가적으로 반영사항이 있다면 자유롭게 말씀주세요!

#### 연관 이슈

- close #270 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-08-11 14:43 UTC, robinjoon requested changes
고생하셨습니다! 코멘트에 남긴 것 처럼 특히나 리팩토링 작업이라면 그 작업을 하게된 배경이나 이유, 왜 개선인건지 등을 기록으로 남겨두는 것이 좋을 것 같아서 RC 드렸어요!

2024-08-11 14:43 UTC, robinjoon commented on backend/src/test/java/develup/api/ApiTestSupport.java
> +}
[Request Change] [공식 문서](https://docs.spring.io/spring-framework/reference/testing/integration.html#testing-ctx-management)에 따르면 일반적인 경우 스프링 컨텍스트를 재사용하지만, 빈의 정의가 변경되는 경우 컨테이너를 다시 만든다고 하네요. 기존 테스트에서 각각 `MockBean` 설정을 했기 때문에 매 테스트마다 빈의 정의가 변경되게 되어 컨테이너가 다시 실행되는 거였군요!

또한, 기존에 API 테스트가 `SpringBootTest` 어노테이션을 사용해 모든 빈이 등록되었고 이로인해 약간의 비효율이 있었던거네요.

아마 아톰도 이런 이유로 개선을 한거라 생각해요. 하지만, 이런 개선 의도를 개선된 코드를 보고 검색을 통해 찾는 것 보단, 작업자가 이런 작업을 한 이유를 PR이나 이슈에 설명을 해준다면 더 좋을 것 같아요! 특히 리팩토링이라면, 팀원들  사이에 지식 싱크를 맞추는 점에서도, 이력서에 어필하는 측면에서도 작업의 근거를 남기는 것이 좋을 것 같네요!

2024-08-12 00:16 UTC, le2sky commented on backend/src/test/java/develup/api/ApiTestSupport.java
> +}
로빈 짚어주셔서 감사해요. PR 본문에 맥락을 남겨놨는데요.
추가 설명이 필요하다면, 편하게 커멘트 남겨주세요. 😀

2024-08-12 00:44 UTC, robinjoon approved these changes

2024-08-12 00:56 UTC, alstn113 approved these changes
[Approve]

ApiTestSupport에 MockBean이 계속 쌓일 것 같은데 걱정이네요.
시간은 얼마나 단축되던가요?

2024-08-12 03:20 UTC, le2sky commented
@alstn113 
프로젝트 초반 단계라 유의미한 성능차이는 보이지 않아요.
제가 아직 부족하여 MockBean 관련해서는 더 나은 대안이 있는지 모르겠네요. 🥲

2024-08-12 05:00 UTC, Minjoo522 approved these changes
아톰 주말동안 고생 많았습니다!
MockBean이 계속 추가되는 것에 대한 고민은 아까 얘기 했었기도 하고 우선은 현재 아톰이 구현해준 방식으로 테스트를 진행하는 것이 최선이라고 생각합니다. 👍

2024-08-12 06:02 UTC, lilychoibb approved these changes
pr 에 설명 잘 해주셔서 좋네요! 
주말에 고생 많으셨어요 아톰 :)

2024-08-12 06:02 UTC, merged