솔루션 댓글 API 구현 (issue #269)
woowacourse-teams/2024-devel-up pull request #292
Opened 2024-08-13 11:05 UTC by alstn113

#### 구현 요약

- 댓글 계층형 조회 api
- 댓글, 답글 생성 api(parentCommentId로 구분해서 생성)
- 댓글 삭제 api

#### 연관 이슈

- close #269 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-08-13 11:39 UTC, alstn113 commented on backend/src/main/java/develup/infra/config/JpaAuditingConfig.java
생성 날짜 처리를 위해서 만들었습니다.
다른 부분들 적용에 대해서 얘기해봐도 좋을 것 같아요. ⛅️

2024-08-13 11:40 UTC, alstn113 commented on backend/src/main/java/develup/domain/IdentifiableEntity.java
pk에 대한 추상 클래스입니다.
슬슬 불편해서 만들었습니다. ⛅️

2024-08-13 11:41 UTC, alstn113 commented on backend/src/main/java/develup/domain/CreatedAtAuditableEntity.java
IdentifiableEntity(pk)를 상속받은 createdAt에 대한 추상 클래스입니다. ⛅️

2024-08-13 11:48 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/CommentGroupingService.java
> +    }
댓글은 RootComment, 답글은 ReplyComment로 설명드리겠습니다.

1. 우선 RootComment를 필터링합니다.
2. RootCommentId가 key이고, ReplyComment 리스트가 value인 map을 만듭니다.
3. 2번에서 만든 ReplyComment 리스트를 RootCommentResponse의 replies 필드에 넣습니다.
4. 삭제되지 않은 RootComment이거나 삭제됐으나 ReplyComment가 있는 것들만 필터링하고 리턴합니다.

2024-08-13 11:50 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/CreateSolutionCommentResponse.java
답글, 댓글 생성 api 호출 시 응답인 dto입니다.

댓글인 경우 getParentComment 시 null이 반환돼 getId시 NPE가 발생합니다.
그래서 18-20줄의 코드를 작성했습니다.

2024-08-13 11:51 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/SolutionCommentRequest.java
> +) {
답글과 댓글을 모두 처리하기 위해서 parentCommentId는 nullable합니다.

2024-08-13 11:53 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/comment/SolutionComment.java
> +        @Index(name = "idx_solution_comment_solution_id", columnList = "solution_id"),
solution을 기준으로 댓글들을 조회하므로 solution_id에 인덱스를 걸었습니다.

2024-08-13 11:57 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/comment/SolutionComment.java
> +    }
create는 일반 댓글 생성을 위함이고, reply는 답글 생성을 위함입니다.

2024-08-13 11:57 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/comment/SolutionComment.java
> +    }
댓글 삭제는 물리 삭제가 아닌 논리 삭제로 LocalDateTime.now() 만 지정해줍니다.

2024-08-14 02:25 UTC, robinjoon requested changes
안녕하세요 구름! 고생 많으셨습니다! 많은 작업들을 해주셨네요! 몇가지 코멘트 남겼으니까 확인해주세요!

2024-08-14 02:25 UTC, robinjoon commented on backend/src/main/java/develup/application/solution/comment/SolutionReplyResponse.java
> +        MemberResponse member,
[Request Change] MemberResponse 에는 이메일 정보가 포함되어있습니다. 개인정보라 판단되는데 이를 API 응답에 포함하면 안된다고 생각합니다.

2024-08-14 02:25 UTC, robinjoon commented on backend/src/main/java/develup/application/solution/comment/CommentGroupingService.java
> +        return repliesMap;
[Request Change]
forEach 대신 collect 와 Collectors 를 이용하면 다음과 같이 작성할 수 있어요.

```Java
return comments.stream()
                .filter(SolutionComment::isReply)
                .filter(SolutionComment::isNotDeleted)
                .collect(Collectors.groupingBy(SolutionComment::getParentCommentId));
```

2024-08-14 02:26 UTC, Minjoo522 requested changes
안녕하세요, 구름!
고생하셨습니다.
변경점이 굉장히 많아서 우선 프로덕션 코드 위주로 리뷰 남깁니다.
이런 경우에는 혹시 작성하셨다면 API 명세나 ERD 구조를 함께 PR 메시지에 남겨 주시면 도움이 될 것 같습니다!

2024-08-14 02:26 UTC, Minjoo522 commented on backend/src/main/java/develup/application/solution/comment/CommentGroupingService.java
> +    }
4번으로 인해서 삭제 필터링을 먼저할 수 없었던 거군요! 이해했습니다. 👍

2024-08-14 02:26 UTC, Minjoo522 commented on backend/src/main/java/develup/application/solution/comment/CreateSolutionCommentResponse.java
> +public record CreateSolutionCommentResponse(
[Comment]

네이밍 `SolutionCommentCreationResponse`는 어떠신가요??
명사가 레코드 명 맨 앞에 있어서 조금 어색하게 느껴집니다 😅

2024-08-14 02:26 UTC, Minjoo522 commented on backend/src/main/java/develup/application/solution/comment/SolutionCommentMapper.java
> +public class SolutionCommentMapper {
[질문]

지금까지 변환 로직이 DTO에 있었던 것으로 기억하는데 여기서만 Mapper를 사용하게된 특별한 이유가 있을까요?

2024-08-14 02:26 UTC, Minjoo522 commented on backend/src/main/java/develup/domain/CreatedAtAuditableEntity.java
> +public abstract class CreatedAtAuditableEntity extends IdentifiableEntity {
[질문]

이 부분에 대한 설명을 듣고 싶습니다. 😅
추상 클래스를 다시 추상 클래스로 구현해야만하는 의도가 있을텐데 코드만 봐서는 이해가 어려워서 설명 해주시면 감사하겠습니다!

2024-08-14 02:26 UTC, Minjoo522 commented on backend/src/main/java/develup/domain/IdentifiableEntity.java
> +public abstract class IdentifiableEntity {
[Comment]

이 추상 메서드가 생기면서 ID를 모든 엔티티마다 정의하지 않아도 되는 장점이 있지만(또 다른 장점도 있다면 알려주시면 감사하겠습니다!) 또 반면에 모든 개발자가 이 추상 메서드의 존재를 알지 못한다면 사용하기 어려운 메서드가 될 것 같기도합니다.
어떤 엔티티는 ID가 명시되어 있고, 어떤 엔티티는 명시되지 않는 상황이 발생할 것 같기도해요.
지금까지 저희는 모든 엔티티에 ID를 명시해왔는데 구름은 이 부분에 대해서 어떻게 생각하시나요?

2024-08-14 02:26 UTC, Minjoo522 commented on backend/src/test/java/develup/application/solution/comment/CommentGroupingServiceTest.java
> +        // given
[Comment]

given-when-then 주석을 사용하지 않는게 컨벤션으로 알고 있는데 혹시 컨벤션에 변경이 있었을까요...?

2024-08-14 04:30 UTC, alstn113 commented on backend/src/test/java/develup/application/solution/comment/CommentGroupingServiceTest.java
> +        // given
까먹고 자율 컨벤션이라고 생각했어요. 일관성을 위해서 다 지웠습니다.

2024-08-14 04:37 UTC, lilychoibb requested changes
안녕하세요 구름 ☁️
빠르게 구현해주셨네요! 고생 많으셨어요 :) 
구름한테 직접 코드에 대해서 설명을 듣기도 했고 질문도 많이 해서 코멘트는 간단한거 몇 가지만 남겼어요. 확인 부탁드려요 🤗

2024-08-14 04:37 UTC, lilychoibb commented on backend/src/main/java/develup/application/solution/comment/SolutionReplyResponse.java
> +        boolean isDeleted
SolutionReplyResponse 에 isDeleted 가 필요한지 의문이네요 🤔 
depth 가 2여서 reply 가 deleted 되면 response 안 줘도 될 것 같아서요!

2024-08-14 04:37 UTC, lilychoibb commented on backend/src/test/java/develup/api/SolutionCommentApiTest.java
> +                .deleteComment(anyLong(), anyLong());
any() 로 통일하자고 했던 것 같아요!

2024-08-14 04:37 UTC, lilychoibb commented on backend/src/test/java/develup/application/solution/comment/CommentGroupingServiceTest.java
> +     */
주석 달아주셔서 이해가 더 쉬운 것 같아요 👍

2024-08-14 04:37 UTC, lilychoibb commented on backend/src/test/java/develup/application/solution/comment/SolutionCommentServiceTest.java
> +        assertThat(foundSolutionComment).isNotNull();
조회된 commentId 와 저장한 commentId 를 비교해도 좋을 것 같아요! (지금도 괜찮긴 합니다)

2024-08-14 04:37 UTC, lilychoibb commented on backend/src/test/java/develup/domain/solution/comment/SolutionCommentTest.java
> +        assertSoftly(softly -> {
assertAll 과 assertSoftly 를 분리해서 사용한 이유가 있을까요?
기준이 궁금합니다!

2024-08-14 04:53 UTC, alstn113 commented on backend/src/test/java/develup/domain/solution/comment/SolutionCommentTest.java
> +        assertSoftly(softly -> {
일관성을 위해서 assertSoftly 을 제거하고 assertAll로 변경했습니다.

2024-08-14 05:02 UTC, alstn113 commented on backend/src/test/java/develup/application/solution/comment/SolutionCommentServiceTest.java
> +        assertThat(foundSolutionComment).isNotNull();
assertThat(foundSolutionComment).isEqualTo(solutionComment);

으로 수정했습니다.

2024-08-14 05:04 UTC, alstn113 commented on backend/src/test/java/develup/api/SolutionCommentApiTest.java
> +                .deleteComment(anyLong(), anyLong());
https://github.com/woowacourse-teams/2024-devel-up/pull/292/commits/a67124ac0a21b1d490c92e232b25819384cbc023

일관성을 위해 anyLong을 지우고 any로 수정했습니다.

2024-08-14 05:07 UTC, alstn113 commented on backend/src/main/java/develup/api/SolutionCommentApi.java
> +        System.out.println(response);
아 이거는 지웠습니다.

2024-08-14 05:32 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/CreateSolutionCommentResponse.java
> +public record CreateSolutionCommentResponse(
StartSolutionRequest, SubmitSolutionRequest
동사(Create),명사(SolutionComment) Response 순으로 맞출려고 했어요.

2024-08-14 05:38 UTC, alstn113 commented on backend/src/main/java/develup/api/SolutionCommentApi.java
> +        return ResponseEntity.created(location).body(new ApiResponse<>(response));
location에 들어가는 거라서 일부러 개행없이 했습니다.

2024-08-14 05:49 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/comment/SolutionComment.java
> +    }
댓글과 대댓글을 분리하면 쿼리가 많이 나갈 것 같아서 그랬어요.

2024-08-14 05:55 UTC, Minjoo522 commented on backend/src/main/java/develup/api/SolutionCommentApi.java
> +        return ResponseEntity.created(location).body(new ApiResponse<>(response));
정의된 컨벤션이 아니라서 기준이 조금 헷갈리네요 😅
혹시 정리된 내용이 있다면 공유해주시면 감사하겠습니다!!

2024-08-14 05:57 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/comment/SolutionComment.java
> +    }
넵 삭제된 댓글도 보이는 경우가 있어서 그랬습니다.

2024-08-14 06:39 UTC, alstn113 commented on backend/src/main/java/develup/api/SolutionCommentApi.java
> +        return ResponseEntity.created(location).body(new ApiResponse<>(response));
https://github.com/woowacourse-teams/2024-devel-up/pull/292/commits/1dd69a946602d98e6290868b186a7e8a40be3940

컨벤션이 없어서 헷갈리긴하네요.
다른 부분과 일관성을 맞춰서 개행했습니다. ⛅️

2024-08-14 06:54 UTC, alstn113 commented on backend/src/main/java/develup/domain/IdentifiableEntity.java
> +public abstract class IdentifiableEntity {
| 이 추상 클래스가 생기면서 ID를 모든 엔티티마다 정의하지 않아도 되는 장점이 있지만
이것과 equals hashcode 재정의를 통해서 동등성 비교 코드를 중복 작성하지 않아도 됩니다.

일단 생성 시간 주입에 대한 추상 클래스를 만들면서 작성했고, "모두 동의"한다면 다른 것들도 변경할 생각입니다.

2024-08-14 06:56 UTC, alstn113 commented on backend/src/main/java/develup/domain/CreatedAtAuditableEntity.java
> +public abstract class CreatedAtAuditableEntity extends IdentifiableEntity {
id 와 id + createdAt인 이유는 생성 시간이 필요 없는 경우도 있어서 분리했습니다.
미션과 같은 경우 id는 필요하지만 생성 시간은 필요 없죠.
생성 시간이 들어가는 곳에 대부분 id가 들어감으로 IdentifiableEntity를 상속받아 CreatedAtAuditableEntity를 만들었습니다.

2024-08-14 07:24 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/SolutionReplyResponse.java
> +        boolean isDeleted
https://github.com/woowacourse-teams/2024-devel-up/pull/292/commits/7639fbae6fbc7c292d64b9a05b6074d8948caabe

넵 구현하면서 착각한 것 같아요. 사용하지 않는 부분이라 CommentMapper도 지우고, dto에서 변환 로직을 가져가도록 변경했어요.

2024-08-14 07:27 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/SolutionCommentMapper.java
> +public class SolutionCommentMapper {
먼저 PR에 자세히 작성하지 않은 점 죄송합니다.

처음으로 CommentMapper를 사용한 이유는 다음과 같아요.
삭제된 댓글인 경우 content, member, created_at을 숨김 처리 할려고 했어요. 
그리고 이 역할은 응답 dto의 역할이라고 생각했어요.
하지만 댓글 응답, 답글 응답 그리고 삭제된 경우에 대한 응답을 처리할려다보니 dto의 역할이 커졌어요.

현재는 https://github.com/woowacourse-teams/2024-devel-up/pull/292#discussion_r1716286252 이 부분을 고치면서 변환 로직을 dto로 옮겼어요. 하지만 if isDeletd에 대한 테스트는 필요할 것 같아서 테스트를 해습니다. ⛅️

2024-08-14 07:28 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/CommentGroupingService.java
> +                    return commentMapper.toRootCommentResponse(it, replies);
https://github.com/woowacourse-teams/2024-devel-up/pull/292#discussion_r1716286252

이 부분에서 createSolutionCommentRepliesResponse로 분리했습니다. ⛅️

2024-08-14 07:29 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/SolutionRootCommentResponse.java
> +public record SolutionRootCommentResponse(
[createSolutionCommentRepliesResponse](https://github.com/woowacourse-teams/2024-devel-up/pull/292/commits/7639fbae6fbc7c292d64b9a05b6074d8948caabe)

SolutionCommentRepliesResponse 좋은 것 같아요. 변경했습니다. ⛅️

2024-08-14 14:17 UTC, lilychoibb approved these changes

2024-08-15 02:14 UTC, robinjoon approved these changes

2024-08-15 09:12 UTC, le2sky requested changes
구름 안녕하세요. 아톰입니다.
너무 늦게 피드백 드려서 죄송합니다. 🥲
다른 분들이 좋은 피드백 남겨주셔서 소소하게 남겼어요.
신경쓸 부분이 많았을텐데 고생 많으셨어요.

2024-08-15 09:12 UTC, le2sky commented on backend/src/main/java/develup/application/solution/comment/SolutionCommentService.java
> +    }
[Request Changes]

조회성 메서드와 사이드 이펙트를 발생시키는 메서드는 함께 모아 두는 것은 어떨까요?

2024-08-15 09:12 UTC, le2sky commented on backend/src/main/java/develup/infra/config/JpaAuditingConfig.java
> +}
[Comment]

infra 내부 config에 존재하여 infra 영역에 대한 전체 설정으로 보여 헷갈릴 수도 있다고 생각해요. `infra/jpa/JpaAuditingConfig.java`는 어떨까요?

2024-08-15 09:40 UTC, Minjoo522 approved these changes

2024-08-15 10:51 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/SolutionCommentService.java
> +    }
getComment와 getComment를 사용하는 deleteComment를 같이 두라는 말씀이실까요?
아직은 getComment를 안쓰는데 나중에 단일 조회를 위해서 public으로 두고 올렸어요.

2024-08-15 10:53 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/SolutionCommentRepliesResponse.java
> +    ) {
https://github.com/woowacourse-teams/2024-devel-up/pull/292/commits/4f45b308e1148523f3de26329d1b832f80bddfbb

of, ofDeletd로 수정했습니다.

2024-08-15 10:53 UTC, alstn113 commented on backend/src/main/java/develup/application/solution/comment/CommentGroupingService.java
> +    private static SolutionCommentRepliesResponse createSolutionCommentRepliesResponse(
https://github.com/woowacourse-teams/2024-devel-up/pull/292/commits/25b68ecdff009bbb6bb22e5075cdbe1e777de4e8

단축키 쓰다가 잘못 들어갔네요. 수정했습니다.

2024-08-15 10:53 UTC, alstn113 commented on backend/src/main/java/develup/infra/config/JpaAuditingConfig.java
> +}
https://github.com/woowacourse-teams/2024-devel-up/pull/292/commits/4920cdbf93bb7f978257971a2c999d06625b1672

config보다 jpa가 적절한 것 같네요. 수정했습니다.

2024-08-15 11:02 UTC, le2sky approved these changes
구름 고생 많으셨습니다. 이만 approve 할게요. 👍

2024-08-15 11:29 UTC, alstn113 commented
Merge하기 전에 혹시 몰라서 local에서 QA해봤습니다. 
경우의 수 여것저것 해봤는데 나중에 에러나면 죄송합니다;;

2024-08-15 11:29 UTC, merged