내가 제출한 솔루션 리스트 조회 기능 구현 (issue #288)
woowacourse-teams/2024-devel-up pull request #293
Opened 2024-08-13 11:14 UTC by lilychoibb

#### 구현 요약

대시보드 페이지 - 내가 제출한 솔루션 리스트 조회 기능 구현

#### 연관 이슈

- close #288 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-08-13 15:33 UTC, le2sky requested changes
릴리 고생 많으셨어요. 
사소한 피드백 몇 가지 투척하고 가요. 👍

2024-08-13 15:33 UTC, le2sky commented on backend/src/main/java/develup/domain/solution/Solution.java
> +    }
[Approve]

이렇게 getter가 합쳐진 형태에서 네이밍이 고민되네요.
getMissionThumbnail이 제일 정확한 표현 같은데, 릴리의 의견은 어떤가요?
릴리의 선호에 따라 반영해주세요.

2024-08-13 15:33 UTC, le2sky commented on backend/src/main/java/develup/domain/solution/SolutionRepository.java
> +    List<Solution> findByMember_IdAndStatus(Long memberId, SolutionStatus solutionStatus);
[Request Changes]

반환값이 리스트인 경우 findBy로 시작하면 다른 개발자가 혼란스러울 수 있어요.
findAll로 시작하는 것은 어떨까요?

2024-08-14 04:00 UTC, alstn113 approved these changes
수고하셨습니다 ⛅️ 👍👍👍👍👍👍👍

2024-08-14 04:13 UTC, robinjoon approved these changes
안녕하세요 릴리! 수고하셨습니다!

반영해주셨으면 하는 코멘트가 있지만, 사소해서 이대로 머지해도 될 것 같아서 approve 드립니다!

2024-08-14 04:13 UTC, robinjoon commented on backend/src/test/java/develup/application/solution/SolutionServiceTest.java
> +        assertThat(solutionService.getSubmittedSolutionsByMemberId(accessor.id())).hasSize(1);
[Comment]

서비스 입장에서 `Accessor`는 외부의 구체적인 구현이라고 생각해요. 그래서 `Accessor` 없이 바로 member.getId() 로 서비스 메서드 호출해도 될 것 같아요!

2024-08-14 04:13 UTC, robinjoon commented on backend/src/test/java/develup/application/solution/SolutionServiceTest.java
> +        assertThat(solutionService.getSubmittedSolutionsByMemberId(accessor.id())).hasSize(1);
[Comment]

서비스 입장에서 `Accessor`는 외부의 구체적인 구현이라고 생각해요. 그래서 `Accessor` 없이 바로 member.getId() 로 서비스 메서드 호출해도 될 것 같아요!

2024-08-14 04:51 UTC, lilychoibb commented on backend/src/main/java/develup/domain/solution/Solution.java
> +    }
반영했습니다👍 현재 상태에선 getter가 합쳐졌다는 것이 명확하진 않네요

2024-08-14 04:52 UTC, lilychoibb commented on backend/src/main/java/develup/domain/solution/SolutionRepository.java
> +    List<Solution> findByMember_IdAndStatus(Long memberId, SolutionStatus solutionStatus);
수정했어요! 신경 못 썼던 부분 봐주셔서 감사합니다 :)

2024-08-14 05:06 UTC, lilychoibb commented on backend/src/test/java/develup/application/solution/SolutionServiceTest.java
> +        assertThat(solutionService.getSubmittedSolutionsByMemberId(accessor.id())).hasSize(1);
solution 을 submit 하는 로직에서 원래 Accessor 가 필요해서 테스트에서 썼었는데, 해당 로직이 지워지면서 불필요한 부분이 되었네요!
이번 pr 테스트에서도 쓰지 않아도 됐었는데, 짚어주셔서 감사합니다 로빈~ 👍

2024-08-14 05:48 UTC, Minjoo522 approved these changes
안녕하세요 릴리 고생많으셨습니다!
다른 팀원들이 좋은 코멘트 남겨주셔서 바로 Approve합니다! 👍👍👍👍

2024-08-14 11:23 UTC, le2sky approved these changes
릴쌤 고생 많으셨어요. 추가 반영 사항 없으시면 머지 부탁드려요. 👍

2024-08-14 14:05 UTC, merged