해시태깅 기능 구현(issue #273)
woowacourse-teams/2024-devel-up pull request #296
Opened 2024-08-13 23:26 UTC by le2sky

#### 구현 요약

이 부분을 제거하고 작업한 내용에 대해서 자유롭게 작성해주세요.

#### 연관 이슈

이 부분을 제거하고 연관된 이슈를 아래와 같이 명시해 닫아주세요.

- close #273

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-08-14 03:49 UTC, le2sky commented
잠시만요 OneToMany Set으로만 바꿀게요..

2024-08-14 07:10 UTC, Minjoo522 approved these changes
안녕하세요, 아톰!
고생했습니다.
깔끔한 코드 인상 깊었습니다. 👍
간단한 리뷰 드리니 참고해주세요!

2024-08-14 07:10 UTC, Minjoo522 commented on backend/src/main/java/develup/domain/mission/Mission.java
> +
[Comment]

일급 컬렉션으로 포장하는 건 어떻게 생각하시나요??

2024-08-14 07:10 UTC, Minjoo522 commented on backend/src/main/java/develup/domain/mission/Mission.java
> +        return Collections.unmodifiableSet(hashTags);
👍

2024-08-14 08:41 UTC, le2sky commented on backend/src/main/java/develup/application/mission/MissionResponse.java
> +        List<HashTagResponse> hashTag
원래는 hashTags가 맞을 것 같은데요. 프룬이랑 명세에 대해서 논의할때 hashTag라고 실수로 정해버린게 굳어버렸어요. 🥲

2024-08-14 08:43 UTC, le2sky commented on backend/src/main/java/develup/domain/mission/Mission.java
> +
현재 컬렉션으로 변경해봤어요. 어색한 부분이 있다면, 추가 피드백 부탁드려요. 🙇🏻‍♂️

2024-08-14 14:03 UTC, lilychoibb approved these changes
고생 많으셨어요 아톰 ⍢ 👍

2024-08-14 14:03 UTC, lilychoibb commented on backend/src/main/java/develup/domain/mission/MissionHashTags.java
> +    private Set<MissionHashTag> hashTags = new LinkedHashSet<>();
혹시 LinkedHashSet 으로 구현하신 의도를 알 수 있을까요? (단순 질문)

2024-08-14 16:51 UTC, robinjoon requested changes
안녕하세요 아톰! 해시태그 기능들 구현하시면서 고생 많으셨습니다!👍 특히, 연관관계가 복잡해지면서 발생하는 신기한 문제들을 해결하는 과정에서 고심하는 아톰이 기억에 남네요.

한가지 질문과 한가지 반영해주셨으면 하는 점 남겼으니 확인해주세요~~😀

2024-08-14 16:51 UTC, robinjoon commented on backend/src/main/java/develup/domain/mission/MissionRepository.java
> +    List<Mission> findAllHashTaggedMission();
[질문]

JPQL 을 직접 작성하신 이유가 Mission이 필요할 때 HashTag 정보가 항상 필요하고, 따라서 로딩 방식에 상관 없이 해시태그를 조회하는 추가 쿼리가 발생하고, 이를 해결하고자 fetch 를 사용하기 위해 작성하신 것 맞나요? 

질문의 의도는 2가지 입니다.

1. JPQL을 사용한 배경이 n+1 문제 해결인지 확인하기 위해
2. 앞으로도 n+1 문제를 해결할 때 `@EntityGraph` 을 사용하지 않고 직접 JPQL 을 작성하는 것이 우리의 표준인지 아니면 여러 방법을 그때 그때 선택해서 작성하는 것인지 확인하기 위해

2024-08-14 16:51 UTC, robinjoon commented on backend/src/test/java/develup/support/data/HashTagTestData.java
> +}
[Approve]

설정할 필드 자체가 없어서 빌더 패턴을 사용하는게 좀 어색하네요. 하지만, 일관성을 위한 선택으로 보여서 넘어가도 좋을 것 같아요!

2024-08-14 16:51 UTC, robinjoon commented on backend/src/test/java/develup/support/data/MissionTestData.java
> +                .withHashTags(Collections.emptyList());
[Request Change]

실제로 미션을 제공할 때 언어 태그는 필수적으로 제공할 것 같아요. 이에 맞게 기본 테스트 데이터에서도 언어 해시태그가 있는 것이 더 좋을 것 같아요!

2024-08-15 02:16 UTC, alstn113 requested changes
궁금한 점들이 다른 분들의 리뷰에 다 달린 것 같아요.

해시태그와 큰 연관은 없지만 궁금한 점이 있어요.
기능 명세서 v2에 작성 날짜, 작성자 정보가 있었는데 반영이 안됐더라구요(물론 디자인도)
제가 듣지 못한 어떤 이유들이 있었을까요?
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/5696e68a-9a82-44a0-a876-a5f49fb90d06">

2024-08-15 02:19 UTC, alstn113 commented on backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
> +    private EntityManagerFactory factory;
[궁금]

이거 사용하지 않는데 필요한건가요?

2024-08-15 10:03 UTC, le2sky commented on backend/src/main/java/develup/domain/mission/Mission.java
> +    public void tagAll(List<HashTag> tags) {
추후에 어드민에서 사용될 것을 염두했었어요. 다만, 지금은 사용처가 없습니다. 지우는 것이 나을까요?

2024-08-15 10:05 UTC, le2sky commented on backend/src/main/java/develup/domain/mission/MissionHashTags.java
> +    private Set<MissionHashTag> hashTags = new LinkedHashSet<>();
hasTags에 add된 순서대로 insert query를 생성하는 것을 기대하고 LinkedHashSet을 사용했었습니다.
검증이 필요한 부분이었는데 놓쳤었네요. 지금 다시 테스트해보니 HashSet을 사용해도 순서를 보장하네요.
다른 구현체를 사용하는 것이 나을까요? 릴쌤의 의견이 궁금해요.

2024-08-15 10:28 UTC, le2sky commented on backend/src/main/java/develup/domain/mission/MissionRepository.java
> +    List<Mission> findAllHashTaggedMission();
n + 1을 해결하기 위해서 JPQL을 사용한다보다는 제가 JPQL을 더욱 좋아한다? 정도로 받아주시면 좋을 것 같아요.
spring data jpa repository의 쿼리가 수정되면 시그니처가 변경되어, 이를 사용하는 응용 계층에도 변경이 전파돼요.
그리고 복잡한 쿼리의 경우 가독성이 낮아진다고 생각합니다.

그리고 두 번째 의도는 앞으로 n + 1 해결할때 `join fetch vs entity graph vs 유도리` 정도로 이해했는데요.
제가 로빈의 질문을 오해했다면 편하게 말씀주세요. 

n + 1 해결할때 앞서 말씀주신것처럼 `join fetch`나 `@EntityGraph`를 사용할 수 있는데요. 
`@EntityGraph` 이 친구는 left join만 제공하는 것으로 알고 있어요. 다른게 필요하면 JPQL이 자유도가 더 높아요.
따라서, 저는 한 가지 정하기 보다는 상황에 맞게 적절히 선택하는게 좋다고 생각해요.

2024-08-15 10:45 UTC, le2sky commented on backend/src/test/java/develup/support/data/MissionTestData.java
> +                .withHashTags(Collections.emptyList());
이 부분 개발하면서 고민했던 부분인데요.
emptyList를 설정한 이유는 mission을 저장할 때 주어지는 HashTag는 저장된 상태여야 한다는 조건이 있기 때문입니다.
따라서 기본 HashTag를 설정해주면, mission을 저장하는 테스트에서 `.withHashTags`를 빈 컬렉션으로 주거나 저장된 HashTag의 List를 `.withHashTags` 안에 추가해줘야하는 번거로움이 존재해요.

추후 언어 해시태그가 필수라는 도메인 제약이 생기면 추가해야할 것 같지만, 아직은 생기지 않은 상태이므로 현상유지하고 싶어요.
제가 놓치고 있는 부분이 있다면, 추가 피드백 부탁드립니다. 🥲

```java
        HashTag hashTag = hashTagRepository.save(HashTagTestData.defaultHashTag().build());
        Mission hashTaggedMission = MissionTestData.defaultMission()
                .withHashTags(List.of(hashTag))
                .build();
        Mission nonTaggedMission = MissionTestData.defaultMission().build();
        missionRepository.saveAll(List.of(hashTaggedMission, nonTaggedMission));

        Optional<Mission> hashTaggedFound = missionRepository.findHashTaggedMissionById(hashTaggedMission.getId());
        Optional<Mission> noneTaggedFound = missionRepository.findHashTaggedMissionById(nonTaggedMission.getId());
```

2024-08-15 10:52 UTC, le2sky commented on backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
> +    private EntityManagerFactory factory;
호우.. 감사합니다.

2024-08-15 10:55 UTC, le2sky commented
@alstn113 
@lilychoibb 

솔루션 응답릴리랑 라이언이랑 함께 만들때 누락된것으로 보이네요. 내일 다시 한번 이야기해볼게요.
짚어주셔서 감사합니다. 🙇🏻‍♂️

2024-08-15 11:04 UTC, le2sky commented on backend/src/main/java/develup/application/mission/MissionResponse.java
> +        List<HashTagResponse> hashTag
++ 현재 프엔들과 합의하에 hashTags로 변경했습니다.

2024-08-15 11:05 UTC, alstn113 approved these changes
수고하셨습니다! 👍👍👍 ⛅️

2024-08-15 11:22 UTC, robinjoon commented on backend/src/main/java/develup/domain/mission/MissionRepository.java
> +    List<Mission> findAllHashTaggedMission();
> spring data jpa repository의 쿼리가 수정되면 시그니처가 변경되어, 이를 사용하는 응용 계층에도 변경이 전파돼요.

이 부분은 생각하지 못한 부분이네요. 👍

2024-08-15 11:24 UTC, robinjoon approved these changes

2024-08-15 11:46 UTC, le2sky reviewed
@lilychoibb 

우선 전체 approve 확인하여 머지할게요.
릴쌤이 질문주신 부분 수정 필요하다고 생각되시면 내일 편하게 말씀주세요!
새로운 이슈파서 작업하도록 하겠습니다.

2024-08-15 11:48 UTC, merged

2024-08-16 02:01 UTC, lilychoibb commented on backend/src/main/java/develup/domain/mission/MissionHashTags.java
> +    private Set<MissionHashTag> hashTags = new LinkedHashSet<>();
아하 의도는 이해했습니다!
> 지금 다시 테스트해보니 HashSet을 사용해도 순서를 보장하네요.

근데 이게 더 이상한데요 ..? 왜 순서가 맞을까요 ㅋㅋㅋㅋ😅

2024-08-16 02:07 UTC, lilychoibb commented on backend/src/main/java/develup/domain/mission/Mission.java
> +    public void tagAll(List<HashTag> tags) {
아직 기획에 어드민이 들어가있지 않긴 한데 있어도 괜찮을 것 같기도 하고 .. 이 부분은 팀원들이랑 얘기 같이 나눠보면 좋겠네요 ☺️!