백엔드 Nginx, Spring docker 컨테이너로 띄우기 (issue #282)
woowacourse-teams/2024-devel-up pull request #302
Opened 2024-08-14 13:09 UTC by Minjoo522

#### 구현 요약

- 해당 PR은 우선 dev 레파지토리에 올라갑니다.

백엔드 Nginx와 Spring을 도커 컨테이너로 띄우기 위한 파일들을 추가했습니다.
현재 https://dev.api.devel-up.co.kr/ 이 주소에서 도커로 실행 중에 있으니 참고해주세요. 👍

#### 연관 이슈

- close #282

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-08-14 14:33 UTC, alstn113 commented on backend/compose.dev.yml
> +    image: ${BACKEND_APP_IMAGE_NAME}
[궁금]

image: ${BACKEND_APP_IMAGE_NAME}
이 부분이 무엇인지 알 수 있을까요?

2024-08-14 14:48 UTC, alstn113 requested changes
수고하셨습니다! 

이번에 구현된 댓글에 생성 시간이 있어요.
EC2 기본 타임존이 UTC라 9시간 전으로 될 것 같아요.

변경 방법은 다음을 참고해주세요. 

1. compose.dev.yml에서 변경
```yaml
environment: 
    TZ: "Asia/Seoul"
```
2. Dockerfile ENTRYPOINT에서 변경
```yaml
ENTRYPOINT ["java", "-Dspring.profiles.active=${SPRING_PROFILE}", \
                "-Duser.timezone=Asia/Seoul", "-jar", "/app.jar"]
```

2024-08-14 14:48 UTC, alstn113 commented on backend/compose.dev.yml
> +    image: ${BACKEND_APP_IMAGE_NAME}
[궁금]

image: ${BACKEND_APP_IMAGE_NAME}
이 부분이 무엇인지 알 수 있을까요?

2024-08-14 14:48 UTC, alstn113 commented on backend/compose.dev.yml
> +      - /home/ubuntu/custom.conf:/etc/nginx/conf.d/custom.conf
[궁금]

서버에 custom.conf라는 파일을 만들어 두고 가져오는 것 같아요. (아마도 🧐)
nginx.conf파일을 두고 버전 관리를 하는 것은 어떨까요?

장점으로는 버전관리, 백업, 협업, 자동화가 있을 것 같은데
단점으로는 보안이나 복잡성이 있을 것 같네요.

2024-08-14 16:12 UTC, robinjoon requested changes
안녕하세요 리브! 완전히 새로운 영역의 작업을 하시느라 여러 어려움이 많을 것 같네요 ㅠㅠ. 그래도 리브라면 잘 하실 수 있을 것 같아요! 실제로도 잘 하고 계시구요😀👍👍👍 다만, 저도 모르는 부분을 작업하고 계신 것이라 더 대화하고 싶어서😅 RC를 드렸어요!

작업하신 부분에서 몇가지 궁금한 부분 코멘트로 남겼어요. 그런데, **한가지 더 궁금한 점**이 있어요. PR을 더 잘 이해하고자 로컬에 풀 받아서 확인을 해보고 있었어요. 이 과정에서 **도커를 이용한 CD 작업을 하신 부분이 dev 브랜치에 바로 커밋된 것을 발견**했어요. 또 파일 변경점을 보려고 찾던 과정에서 [이전 PR](https://github.com/woowacourse-teams/2024-devel-up/pull/281) 에서 머지된 [커밋](https://github.com/woowacourse-teams/2024-devel-up/commit/638000c6d415eabe904ed993aa63d6523108832b)이 유실된 것도 확인할 수 있었어요. **의도된 것인지, 어떤 실수가 있었던 것인지 궁금**합니다! 

**비판하거나 하는 의도는 전혀 없고 저도 도커를 이용한 CD 워크플로우를 처음 경험하는 것(사실 제가 하고 싶기도 했어요😅)이라 너무너무 궁금해서 질문드려요~**

2024-08-15 08:28 UTC, le2sky requested changes
리브 사소한 코멘트 하나 남겼어요.
제가 잘못알고 있는 부분이 있다면, 추가 설명 부탁드립니다
고생 많으셨습니다. 👍👍👍

2024-08-15 08:28 UTC, le2sky commented on backend/compose.dev.yml
> +      - "8080:8080"
[Comment]

ports와 EXPOSE(Dockerfile 내부)는 비슷한 옵션으로 알고 있는데 맞을까요? 
그리고, 이를 떠나 컨테이너 외부로 8080 포트를 노출할 필요가 없어보이는데요.
리브의 의견은 어떠신가요? 제가 놓치고 있는 부분이 있다면 추가 설명 부탁드려요! 😀

2024-08-15 08:33 UTC, le2sky commented on backend/compose.dev.yml
> +      - "8080:8080"
아 엑츄에이터..?

2024-08-15 08:37 UTC, Minjoo522 commented on backend/compose.dev.yml
> +    image: ${BACKEND_APP_IMAGE_NAME}
로빈 추측이 맞습니다.
2번을 선택한 이유는 1번을 선택할 경우에 환경 변수 변경이 있는 경우 직접 서버에 접속해서 변경해야하기 때문입니다!

추가적으로 CD 과정 중에 env 파일을 실행 파일이 있는 곳에 만든 후 docker compose up을 하는 방법도 있습니다.
이 방법을 채택하지 않은 이유는 현재는 필요한 환경 변수가 하나밖에 없어서 불필요하다고 느꼈습니다.
추후 docker에 필요한 환경 변수가 많아지면 적용하는게 좋을 것 같습니다.

2024-08-15 08:46 UTC, Minjoo522 commented on backend/compose.dev.yml
> +      - "8080:8080"
> The EXPOSE instruction doesn't actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published. To publish the port when running the container, use the -p flag on docker run to publish and map one or more ports, or the -P flag to publish all exposed ports and map them to high-order ports.

EXPOSE는 컨테이너가 내부적으로 8080 포트를 사용한다고 명시하는 문서화 역할을합니다! 😊
직접 포트 개방을 하기 위해서는 ports에 지정해주어야합니다.
그리고 스프링 기본 옵션이 8080이기도하고 저희가 다른 포트를 사용하지 않고 nginx에서 포트 포워딩까지 하고 있기 때문에 포트 노출을 하지 않아야 좋겠다는 생각까지는 하지 못했습니다. 😭
필요하다면 환경 변수로 지정할 수 있겠지만 노출하는 게 혹시 문제가 있는걸까요...?(잘 몰라서 여쭤봅니당)

2024-08-15 08:54 UTC, Minjoo522 commented on backend/compose.dev.yml
> +      - nginx-app-net
별도 설정을 해주지 않아도 default 네트워크로 묶이긴 합니다!
하지만 네트워크를 명시하고 네트워크 격리하기 위해 사용했습니다.
네트워크를 명시하면 두 컨테이너는 연관 관계가 있기 때문에 같이 관리가 되어야 한다는 걸 바로 알 수 있다고 생각했습니다.

그리고 아직 도입하지는 않았지만 저희가 구조도를 설계할 때 dev 서버에서는 db를 같이 위치시키기로 했었습니다.
nginx와 저희 application을 미리 networks로 묶어두면 다음 개발자에게도 db와 application도 따로 networks를 묶어두어야 한다는 걸 묵시적으로 전달할 수 있을거라고 생각했습니다!(물론 직접 말이나 문서로 또 해야할수도 있겠지만 ㅋㅋ)

2024-08-15 09:04 UTC, Minjoo522 commented on backend/compose.dev.yml
> +      - /home/ubuntu/custom.conf:/etc/nginx/conf.d/custom.conf
> nginx.conf파일을 두고 버전 관리를 하는 것은 어떨까요?
이거는 github에서 관리를 하는 거를 말하시는 걸까요?

서버에 파일을 만들어둔건(지금은 초기 단계라서 논외일수도 있겠지만) 일단 저희 전체 서비스 아키텍처가 잡히고 나면 conf 파일이 바뀔 일이 거의 없을 거라고 생각했습니다!
그리고 github에서 관리를 하게 되는 경우에는 변동 사항이 있는 경우 변동사항을 push한 후 서버에서 pull하는 과정이 필요합니다. (이 과정도 github actions를 사용해서 자동화 할 수 있겠지만 장점에 비해 복잡성이 높지 않을까 싶습니다.)

2024-08-15 09:12 UTC, Minjoo522 commented on backend/compose.dev.yml
> +      - /home/ubuntu/custom.conf:/etc/nginx/conf.d/custom.conf
- https://github.com/woowacourse-teams/2024-devel-up/pull/302#discussion_r1718161685 참고해주세요!

추가적으로 서브모듈에서 관리하게 되는 경우에 github actions에서 변동 사항이 있음을 잡아내지 못하기 때문에 변경 후 cd 작업이 트리거 되지 않습니다. 이런 경우 cd 작업을 직접 다시 트리거 해줘야합니다.
깃허브 액션에서 default 브랜치가 아니면 매뉴얼하게 워크플로우를 실행할 수가 없어서 억지로 트리거 해줘야하는 상황(자바 파일에 주석 추가하거나 하는 방법으로...)이 발생할 것 같습니다.

프로덕션 서버를 위한 브랜치에서는 고려해볼만 할 것 같습니다.

2024-08-15 09:25 UTC, le2sky commented on backend/compose.dev.yml
> +      - "8080:8080"
아하 그렇군요. 알려주셔서 고마워요 리브 🙇🏻‍♂️
단순하게 접근 못하는 포트를 불필요하게 열필요는 없겠다고 생각했었어요.
음.. 다시 생각해보니 열어야할 것 같다는 생각이 드네요. 이야기가 조금 길어질 것 같아서 슬랙에서 다시 말씀드릴게요!
지금은 approve 처리하겠습니다.

2024-08-15 09:26 UTC, le2sky approved these changes

2024-08-15 11:13 UTC, alstn113 commented on backend/compose.dev.yml
> +      - nginx-app-net
다른 예시에서 컨벤션 느낌으로 networks를 정의하더라구요.
그래서 default 네트워크로 엮이는 줄 몰랐네요. 감사합니다 ⛅️
그래도 명시적으로 networks를 적는게 이해하기 편할 것 같아요!

2024-08-15 11:30 UTC, robinjoon approved these changes
궁금한 사항들도 다 해소되서 승인합니다! 수고하셨어요~~👍 🍀

2024-08-15 23:50 UTC, Minjoo522 commented
@robinjoon 

> 작업하신 부분에서 몇가지 궁금한 부분 코멘트로 남겼어요. 그런데, 한가지 더 궁금한 점이 있어요. PR을 더 잘 이해하고자 로컬에 풀 받아서 확인을 해보고 있었어요. 이 과정에서 도커를 이용한 CD 작업을 하신 부분이 dev 브랜치에 바로 커밋된 것을 발견했어요. 또 파일 변경점을 보려고 찾던 과정에서 https://github.com/woowacourse-teams/2024-devel-up/pull/281 에서 머지된 [커밋](https://github.com/woowacourse-teams/2024-devel-up/commit/638000c6d415eabe904ed993aa63d6523108832b)이 유실된 것도 확인할 수 있었어요. 의도된 것인지, 어떤 실수가 있었던 것인지 궁금합니다!

이 부분 제가 생각하는 작업 플로우가 공유되지 않아서 그런것 같네요. ㅎㅎ
우선 다른 백엔드 개발자 확인 용도로 PR을 작성했는데 브랜치 분리 및 서버 구조 변경 완성을 메인(prod) -> 개발(dev)로 생각했습니다.
물론, 개발 -> 메인 단계로 가는게 좋지만 계속해서 메인에 머지가되고 변경이 있는 상황이라 불가피했습니다. 물론, 체리픽으로 커밋들을 가져오는 방법도 있지만 체리픽 과정에 충돌이 있는 경우 제가 작업자가 아닌 커밋임에도 불구하고 제가 추가될 가능성이 있고 그렇게까지 복잡하게 할 필요가 없다고 생각했습니다. ^^;
이렇기 때문에 이전 머지된 커밋도 결국 필요가 없어질 거라고 생각했습니다. (그 PR을 올릴 당시에만해도 개발 -> 메인으로 할 예정이었습니다.)

그리고 현재 dev 브랜치에 커밋된 CI/CD는 메인 브랜치에도 올라갈 예정이고 완전 동일한 파일이 올라갈 것이기 때문에(dev -> main 머지시 충돌 방지) 메인에 업로드 할 때 이슈와 PR을 올리는 것이 낫겠다고 생각했습니다.

그럼 또 왜 Dockerfile과 compose, submodules는 왜 올렸나? 생각하실수도 있겠는데요.
제가 도커로 인프라 구성할 예정이라는 것은 모두에게 공유되었지만 그 상세한 과정은 말로 설명하는 것보다 코드로 공유하는 게 더 낫겠다고 생각했습니다.(게다가 작업 하다보면 여러 문제로 제가 말한거랑 또 달라질수도 있겠다고 생각했구요. 저도 처음이라)
추가로 서브모듈은 작업할 것이다라고만 하고 어떤 패키지에 어떻게 들어갈지도 어떻게 들어갈지도 코드로 보여드리면 한 눈에 알 수 있구요.

그래도 CI/CD를 커밋하진 않아도 되는거 아니냐?고 물으실 수 있을 것 같은데 이 이유는 단순합니다. 이 커밋 자체가 도커 CD를 전제로 만들어졌기 때문이에요. 로빈처럼 직접 받아서 확인하실 경우에 편의성을 위해 미리 커밋해두었습니다.

다수의 협업으로 프로젝트를하는건 처음이라 생각보다 많은 부분을 공유해야한다는 사실을 간과했네요. 물어봐주셔서 감사합니다!

2024-08-15 23:58 UTC, robinjoon commented
> 그래도 CI/CD를 커밋하진 않아도 되는거 아니냐?고 물으실 수 있을 것 같은데 이 이유는 단순합니다. 이 커밋 자체가 도커 CD를 전제로 만들어졌기 때문이에요. 로빈처럼 직접 받아서 확인하실 경우에 편의성을 위해 미리 커밋해두었습니다.

개인적으로는 말씀하신것 처럼 CD 스크립트가 전제된 내용이었기 때문에 이번 PR에 ci cd 스크립트도 포함되었다면 좀 더 쉽게 전체적인 상황을 파악할 수 있었을 것 같아요. 아무튼 어떤 상황이었는지는 알겠네요~

2024-08-16 00:00 UTC, Minjoo522 commented
@alstn113 

상세하게 알려주셔서 감사해요 구름!
compose 파일에 반영하였습니다.
(참고로 명령어 부분에 넣는 것보다 더 한눈에 들어오고 유지보수도 편할것 같다고 생각해서 compose에 넣는 방법으로 반영했습니다!)

2024-08-16 00:15 UTC, alstn113 approved these changes

2024-08-16 04:49 UTC, lilychoibb approved these changes
리브 고생 많으셨습니다! 👍👍👍👍

2024-08-16 05:02 UTC, merged