내가 작성한 댓글(솔루션) 목록 조회하는 API 구현(issue #326)
woowacourse-teams/2024-devel-up pull request #331
Opened 2024-08-19 08:31 UTC by robinjoon

#### 구현 요약

내가 작성한 댓글(솔루션) 목록 조회하는 API 구현했습니다.

필요한 정보가 기존의 댓글 조회 API와 달라서 관련 DTO 객체들 새로 정의했습니다.

#### 연관 이슈

- close #326

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-08-19 11:03 UTC, robinjoon commented
@alstn113 https://github.com/woowacourse-teams/2024-devel-up/pull/331/commits/7e42a002df43fcb6c585ef06ef04cef2ee3fed4a 수정 했어용

2024-08-19 11:41 UTC, alstn113 approved these changes
[Approve]

repository가 아닌 service 테스트인 이유가 있나요?

2024-08-19 13:23 UTC, le2sky requested changes
로빈 안녕하세요. 아톰입니다.
사소한 커멘트 남기고 가요. 시간 나실 때 편하게 반영해주세요.
고생 많으셨습니다. 😀

2024-08-19 13:23 UTC, le2sky commented on backend/src/main/java/develup/api/SolutionCommentApi.java
> +    @Operation(summary = "내가 솔루션에 단 댓글 조회 API", description = "내가 솔루션에 단 댓글 목록을 조회합니다. 댓글 정보와 댓글이 달린 솔루션의 일부 정보를 조회합니다.")
[Comment]

해당 부분의 독자는 클라이언트 개발자라고 생각해요.
`내가`보다 `사용자`가 더욱 적합할 것 같다고 생각했어요. 
로빈의 의견은 어떠세요? 로빈의 선호에 따라 반영해주세요.

2024-08-19 13:23 UTC, le2sky commented on backend/src/main/java/develup/domain/solution/comment/MySolutionComment.java
> +
[Comment]

불필요한 공백 발견했어요! 👀

2024-08-19 16:24 UTC, Minjoo522 requested changes
안녕하세요, 로빈!
짧은 시간에 기능 개발하느라 고생했습니다.
간단한 코멘트 남기니 확인 부탁드립니다.

2024-08-19 16:24 UTC, Minjoo522 commented on backend/src/main/java/develup/domain/solution/comment/SolutionCommentRepository.java
> +    List<MySolutionComment> findAllMySolutionComment(Long memberId);
[Comment]

기존에 JPQL을 이용한 repository 메서드가 있으면 repository test도 했었던 것 같은데 이 부분도 테스트가 있어야통일성이 있을 것 같습니다.

2024-08-20 01:43 UTC, robinjoon commented on backend/src/main/java/develup/api/SolutionCommentApi.java
> +    @Operation(summary = "내가 솔루션에 단 댓글 조회 API", description = "내가 솔루션에 단 댓글 목록을 조회합니다. 댓글 정보와 댓글이 달린 솔루션의 일부 정보를 조회합니다.")
반영했습니다! https://github.com/woowacourse-teams/2024-devel-up/pull/331/commits/2be1a1b20bea8f2557780a7be0e6e67b18cb3df4

2024-08-20 01:44 UTC, robinjoon commented on backend/src/main/java/develup/domain/solution/comment/MySolutionComment.java
> +
반영했습니다! https://github.com/woowacourse-teams/2024-devel-up/pull/331/commits/ee967c8ddee020c74b57c43fd3c9d9591bd50887

2024-08-20 01:46 UTC, robinjoon commented on backend/src/main/java/develup/domain/solution/comment/SolutionCommentRepository.java
> +    List<MySolutionComment> findAllMySolutionComment(Long memberId);
앗 그렇군요! 플젝에서 제가 JPQL로 메서드 구현한게 이번이 처음이라 실수를 했네요! 기존에 서비스 테스트를 레퍼지토리 테스트로 변경했습니다. 서비스에 별도 로직이 없어 서비스 테스트는 삭제했습니다. https://github.com/woowacourse-teams/2024-devel-up/pull/331/commits/64320aefbd02b1e4bdaf6a3403af0def619f3194

2024-08-20 02:18 UTC, Minjoo522 approved these changes

2024-08-20 02:22 UTC, le2sky approved these changes

2024-08-20 02:22 UTC, le2sky commented on backend/src/main/java/develup/api/SolutionCommentApi.java
> +    @Operation(summary = "사용자가 솔루션에 단 댓글 조회 API", description = "사용자가 솔루션에 단 댓글 목록을 조회합니다. 댓글 정보와 댓글이 달린 솔루션의 일부 정보를 조회합니다.")
👍👍

2024-08-20 03:11 UTC, merged