풀이 삭제 기능 구현(issue #422)
woowacourse-teams/2024-devel-up pull request #423
Opened 2024-09-04 15:22 UTC by le2sky

#### 구현 요약

풀이 삭제 기능을 구현했습니다. (설명 작성 중)

#### 연관 이슈

- close #422

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-09-04 23:56 UTC, le2sky commented on backend/src/main/java/develup/application/solution/SolutionService.java
> +        solutionRepository.delete(solution);
풀이를 삭제하면, 관련 댓글들도 삭제되는 방식으로 구현했어요. 우선 이렇게 연쇄적으로 삭제되는 부분은 기획에서 언급된 적이 없기 떄문에 임의로 선택했습니다. 염려되는 부분이 있다면 편하게 말씀주세요. 

그리고 이 부분을 구현하기 위해서 one to many casecade 옵션을 사용했었는데요.
댓글을 삭제하는 과정에서 n + 1 문제가 발생했었어요. (jpa casecade.remove n + 1 키워드) 이 부분을 풀어내기 위해서는 다음과 같은 선택지들이 있었습니다.

- one to many casecade.remove 유지(n + 1 발생)
- `@OnDelete`를 사용(ddl 변경)
- jpql로 명시적으로 댓글 삭제

구름과 의논하여 jpql을 사용하기로 결정했는데요. 추가 쿼리를 발생시키거나, ddl을 조작하는 것보다 명시적인 쿼리 하나만을 추가로 사용하는 것이 낫다고 핀딘헸습니다. 더 좋은 의견 있으시면 피드백 편하게 남겨주세요.

2024-09-05 07:16 UTC, alstn113 requested changes
구현하느라 수고하셨습니다 👍👍👍👍

수정 사항 코멘트로 남겼어요!

2024-09-05 07:16 UTC, alstn113 commented on backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
> +
[Request Changes]

빈 줄이 생겼어요.

2024-09-05 07:16 UTC, alstn113 commented on backend/src/main/java/develup/api/SolutionApi.java
> +    @DeleteMapping("/solutions")
[Request Changes]

DELETE /solutions/{solutionId} 가 일반적이지 않나요?

2024-09-05 07:16 UTC, alstn113 commented on backend/src/main/java/develup/domain/solution/SolutionRepository.java
> +    void deleteAllComments(Long solutionId);
[Approve]

다음 내용 확인했습니다!

1. 솔루션 삭제 -> 연관된 댓글 삭제
2. 댓글 삭제 방법은 N+1 문제로 JPQL + Modifying 사용

2024-09-05 22:54 UTC, le2sky commented on backend/src/main/java/develup/api/SolutionApi.java
> +    @DeleteMapping("/solutions")
제가 놓쳤던 부분이네요. 반영했습니다! 👍

2024-09-05 22:55 UTC, le2sky commented on backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
> +
오호.. 감사합니다. 이걸 찾아주셨네요.

2024-09-05 23:03 UTC, alstn113 approved these changes
수고하셨습니다

2024-09-06 08:37 UTC, merged