디스커션 도메인 작성 (issue #426)
woowacourse-teams/2024-devel-up pull request #430
Opened 2024-09-06 08:54 UTC by alstn113

#### 구현 요약

- 제목
- 내용
- 작성자
- 미션(태그용) (없을 수도 있다)
- 해시 태그 (없을 수도 있다.)

MissionHashTags와 다르게 Set이 아닌 List로 변경할 수 있어서 변경했습니다.
MissionHashTags는 Solution -> Mission -> HashTag를 찾기 때문에 Set이었음을 기억해주세요!!

비즈니스 로직을 구현하지는 않았고 다른 분들이 개발할 수 있게 도메인만 작성했습니다!!

#### 연관 이슈

- close #426 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-09-06 10:25 UTC, le2sky approved these changes
고생 많으셨습니다! 👍

2024-09-06 10:25 UTC, le2sky commented on backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
> +    private List<DiscussionHashTag> hashTags = new ArrayList<>();
다른 분들을 위해서 추가 설명 드려요.

solution -> mission -> missionHashTags -> hashTag 

위와 같은 관계에서 solution을 기준으로 mission join fetch, missionHashTags join fetch, hashTag join fetch을 수행하면 category 수가 뻥튀기되어 나옵니다. (키워드: oneToMany fetch join 카티션 프로덕트)

이를 해결하기 위해서 distinct 키워드를 jpql에서 사용할 수 있는데요.
정상적으로 중복이 해결되지 않아요. solution은 distinct 키워드로 제거되는데, mission은 distinct 키워드로 제거되지 않았다는 추측입니다.

이러한 해결책으로 missionHashTags 자료구조를 Set을 사용했었어요.
하지만, 위와 같은 문제가 우선 discussion에서는 없으니 List 자료형을 사용했습니다.

2024-09-07 06:43 UTC, robinjoon requested changes
안녕하세요 구름! 해시태그 관련해서 반영했으면 하는 리뷰있어서 달아뒀어요~

2024-09-07 06:43 UTC, robinjoon commented on backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
> +    private List<DiscussionHashTag> hashTags = new ArrayList<>();
[Request Change]

@le2sky @alstn113 
저는 JPA 문제를 떠나서 **디스커션이 같은 해시태그를 중복해서 가질 수 없기 때문에 List가 아니라 Set을 사용해야 한다**고 생각합니다. 
아래 테스트코드에서 **디스커션이 같은 해시태그를 중복해서 가질 수 없도록** 테스트가 작성되어있기 때문에 이를 구현하는 내부 로직에서 List를 사용하는 것 보다 Set을 사용하는 것이 타당하다 생각해요.

2024-09-07 10:21 UTC, lilychoibb commented on backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
> +    private List<DiscussionHashTag> hashTags = new ArrayList<>();
(궁금) 흠 그런데 discussion 상세 페이지에서도 해시태그를 보여준다고 하면, 결국 solution 처럼 join fetch 때문에 카티션 프로덕트 문제가 발생하지 않을까요?

2024-09-07 11:53 UTC, le2sky commented on backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
> +    private List<DiscussionHashTag> hashTags = new ArrayList<>();
@lilychoibb
릴리도 이미 잘 아시겠지만, 미래를 가정하자면 페이지네이션을 사용하면 jpql distinct, Set으로 n + 1해결이 안되지 않나요?
이때는 `@BatchSize`를 사용하거나 다른 방법을 사용해야하는 것으로 알고 있어요. 그럼 결국에 List vs Set에 대해서는 다시 이야기할 필요성이 있지 않을까요? 제가 놓치고 있는 부분이 있으면 편히 말씀 주세요. 😀

2024-09-07 12:01 UTC, le2sky commented on backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
> +    private List<DiscussionHashTag> hashTags = new ArrayList<>();
@robinjoon 

굿굿 👍👍 좋은 의견 감사합니다. 그래도 JPA를 사용하고 있으니 JPA에 대한 이야기는 계속해봐야할 것 같아요.
Set을 사용했을 때 부작용은 없을까요? 질문의 의도는 Set을 부정하는게 아닌 List vs Set에서 저희의 상황에서 어떤것이 나을지 고민하자는 차원입니다!

2024-09-07 15:19 UTC, lilychoibb commented on backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
> +    private List<DiscussionHashTag> hashTags = new ArrayList<>();
@le2sky 
아하 결국 n+1 이 해결 안되는 건 마찬가지이다 이군요! 👍👍 이해됐어요 :)
그런데 missionHashTags 는 Set 으로 일단 해결이 되는 상황이어서 적용하신 걸까요?? 아니면 Set 의 n+1 문제 해결과 도메인 특성 상 LinkedHashSet 이 함께 필요한 상황이니 추후에 List vs Set 에 대한 이야기를 하지 않고 다른 해결책을 도입할 수 있어서일까요? (아톰이 위에 '이러한 해결책으로 missionHashTags 자료구조를 Set을 사용했었어요.' 라고 남겨주어서 제가 헷갈리고 있는 것 같아요🥹)

2024-09-07 15:34 UTC, le2sky commented on backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
> +    private List<DiscussionHashTag> hashTags = new ArrayList<>();
@lilychoibb 
제가 설명을 잘 전달했어야했는데 죄송합니다. 🥲
릴리의 질문을 왜 missionHashTags는 Set 자료구조를 선택했는지가 맞을까요? 제가 오해하고 있는 부분이 있다면, 말씀 주세요!

2024-09-07 16:35 UTC, lilychoibb commented on backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
> +    private List<DiscussionHashTag> hashTags = new ArrayList<>();
@le2sky 
네네! 아톰이 잘 설명해주셨는데 제가 이해가 부족한 것 같아요🥹
질문의 의도는 '왜 missionHashTags는 Set 자료구조를 선택했는지' 가 맞고, 
제가 추측한 이유로는
1. 일단 Set 으로 n+1 문제가 해결이 된다 또는
2. Set 의 n+1 문제 해결도 되고 도메인 특성상 LinkedHashSet 이 함께 필요한 상황이다
입니다!

헷갈린 이유는 '이러한 해결책으로 missionHashTags 자료구조를 Set을 사용했었어요.' 라고 하셨는데, 같은 상황에서 discussion 에서는 '미래를 가정하자면 페이지네이션을 사용하면 jpql distinct, Set으로 n + 1해결이 안되지 않나요?' 라고 말씀해주셔서요!
당연히 LinkedHashSet 도 이유가 되겠지만, n+1 문제 해결 관점으로 봤을 때 입니다!

아톰이 말씀 주신 것에 꼬투리를 잡는 것이 아니라, 제가 잘 모르는 부분이라 이해하고 싶어서 자세하게 여쭤봅니다 🥹☺️

2024-09-08 03:09 UTC, le2sky commented on backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
> +    private List<DiscussionHashTag> hashTags = new ArrayList<>();
missionHashTags의 경우 선택의 여지가 없이 Set만 사용할 수 있었어요.

페이지네이션을 고려하자면, solution -(manyToOne)-> mission -(oneToMany)-> missionHashTags까지 `@BatchSize`로 해결할 수 있는데요.
missionHashTags -(manyToOne)-> hashTag 부분에서 n + 1 문제가 다시 발생할 수 있어 BatchSize로도 완벽히 해결이 불가능하다고 판단했어요. 이를 해결하기 위해서는 쿼리를 분할하는 방식을 떠올려 볼 수 있는데요.
현재 페이지네이션을  고려하지 않는점, 조기 최적화로 인한 복잡도가 증가한다는 점을 고려하여 fetch join과  distinct를 사용해 간단히 n + 1을 해결하는게 낫다고 판단했습니다.

mission의 경우에는 다음과 같은 jpql로 카티션 프로덕트 문제를 해결할 수 있어요.
```
      SELECT DISTINCT m
            FROM Mission m
            JOIN FETCH m.missionHashTags.hashTags mhts
            JOIN FETCH mhts.hashTag ht
            WHERE m.id = :id
```

하지만 문제는 solution 부터인데요. 다음과 같은 경우 distinct가 s에 걸려있음에도 불구하고 missionHashTag가 뻥튀기 되어서 나왔어요. mission에 distinct가 걸려있지 않아서 이런 문제가 발생했다고 추측했습니다. 정확한 원인 분석이 복잡해 우선 mission의 missionHashTags를 Set으로 사용하는 방식으로 해결했습니다.

```
       SELECT DISTINCT s
            FROM Solution s
            JOIN FETCH s.mission m
            JOIN FETCH m.missionHashTags.hashTags mhts
            JOIN FETCH mhts.hashTag ht
            WHERE
                s.status = 'COMPLETED' AND
                EXISTS (
                   SELECT 1
                   FROM MissionHashTag smht
                   JOIN smht.hashTag sht
                   WHERE
                       smht.mission.id = m.id AND
                       (LOWER(:name) = 'all' OR sht.name = :name)
```

hashTags의 Set을 List로 바꿔보시고 http://localhost:8080/solutions 로 GET 요청을 보내면, 아래와 같이 데이터가 중복되어서 나옵니다. 

<img width="905" alt="image" src="https://github.com/user-attachments/assets/dd38e55d-4dca-4ead-a21c-10a3b49208ea">

2024-09-08 07:14 UTC, alstn113 commented
@le2sky @robinjoon 

Set이 맞긴 해요. 근데 저는 해시태그의 순서도 항상 같은 순서로 내려주고 싶었어요.
Set을 하면 @OrderBy(value = "id ASC"), LinkedHashSet을 써야 하잖아요. 그게 번거롭다고 생각했어요.

이 부분을 보다보니 든 생각인데 DiscussionHashTag도 마찬가지고 MissionHashTag도 그렇고 id가 있어요. 
미션마다 같은 해시태그가 존재하지 않는다면 id를 빼야할 것 같아요. 

빨리 만들고 끝낼려고 했는데 상당히 길어지네요 죄송합니다,,,

2024-09-08 07:27 UTC, Minjoo522 commented
저는 좀 새로운 관점으로 생각했는데, Set, List에 관한 논의와는 관련이 없는 것 같지만 일단 적어봅니다.

현재 우리 서비스에서 해시태그는 사용자가 직접 생성하는 것이 아닌 주어진 해시태그를 `선택` 하는 것인데요,
여기서 중복된 데이터가 들어왔다는 건 사용자가 잘못한 게 아니라 프론트 측에 어떤 문제가 있다는 것이겠죠.
근데 프론트 측에 문제가 있다고 글쓰기 자체가 불가하다는 게 사용자에게 불편함을 주는 건 아닐까 생각했습니다.

그래서 애초에 request로 해시태그 아이디가 들어왔을 때 중복 데이터를 한 번 걸러줘야한다고 생각합니다.
즉, 중복된 해시태그가 들어왔다고 예외 메시지를 보내는 게 아니라 서버 측에서 거를 걸 거르고 글 저장이 되도록 해야 한다고 생각해요.

2024-09-08 07:59 UTC, alstn113 commented
@Minjoo522 @le2sky @robinjoon @lilychoibb 

빠르게 머지하기 위해서 의견을 모아봤습니다. ⛅️

우선 Set으로 변경하기 위해서 고유한 id를 가지는게 아닌 DiscussionId와 HashTagId를 복합키로 변경했습니다.
순서도 중요하다고 생각해서 OrderBy와 LinkedHashSet을 적용했습니다.

중복될 일도 없긴하겠지만 만약 중복된다고 예외가 나는 것은 사용자 관점에서 좋지 않다고 의견에 동의해서 예외 처리 부분을 제거했습니다.

더 이상한 부분은 리팩토링 이슈를 파서 진행해보죠! 수고하십쇼 🫡

2024-09-08 08:02 UTC, robinjoon approved these changes
오 다들 열심히 토론해 주셨네요!!! ㅎㅎ 여러 관점을 생각해 볼 수 있겠군요. 우선 작업이 급하니까 승인하고 필요한 거 있으면 새로 이슈 팝시다!

2024-09-08 08:21 UTC, lilychoibb commented on backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
> +    private List<DiscussionHashTag> hashTags = new ArrayList<>();
@le2sky 
오 자세한 설명 감사해요 아톰 ☺️👍👍

2024-09-08 08:29 UTC, merged