디스커션 글쓰기 기능 구현 (issue #437)
woowacourse-teams/2024-devel-up pull request #438
Opened 2024-09-08 12:39 UTC by Minjoo522

#### 구현 요약

- 디스커션 제출 기능을 구현했습니다.
- 미션과 해시태그가 태깅되지 않아도 저장되도록 구현했습니다.

#### 연관 이슈

- close #437

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-09-09 04:20 UTC, le2sky requested changes
리브 안녕하세요. 아톰입니다.
구현 고생 많으셨어요. 👍👍
사소한 커멘트 하나 남겼는데 확인 부탁드립니다.

2024-09-09 04:20 UTC, le2sky commented on backend/src/main/java/develup/application/discussion/DiscussionService.java
> +    }
[Request Changes]

```java
List<HashTag> hashTag = hashTagRepository.findByIdIn(hashTagIds) ;
```

위와 같이 사용하면 쿼리의 수를 줄일 수 있을 것 같아요!

2024-09-09 05:20 UTC, alstn113 requested changes
미션하느라 바빴을텐데 빠르게 구현하느라 수고하셨습니다. 👍👍👍

개인적으로 수정이 필요하다고 생각하는 부분 코멘트 남겼습니다!

2024-09-09 05:20 UTC, alstn113 commented on backend/src/main/java/develup/domain/discussion/Discussion.java
> +
[Comment]

List 변경을 Discussion이 하는게 아닌 MissionResponse 처럼 dto에서 하는게 적합할 것 같아요.

2024-09-09 05:20 UTC, alstn113 commented on backend/src/main/java/develup/application/discussion/DiscussionService.java
> +    }
[Request Changes]

Discussion을 생성할 때 HashTag가 없는 경우 저는 빈 배열을 받을 것으로 기대하고 있어요. null 체크를 위해서 이 부분과 DiscussionHashTags의 mapToDiscussionHashTag에서 null 체크를 하는 것은 과하다고 생각해요

그보다 SubmitDiscussionRequest에서 `@NotNull List<Long> hashTagIds`를 하는 것은 어떨까요?? ⛅️

2024-09-09 08:09 UTC, Minjoo522 commented on backend/src/main/java/develup/api/DiscussionApi.java
> +    }
ResponseEntity.ok 부분은 created가 맞는 것 같은데 Solution에서 ok로 해서 고민이네요. 
저도 created가 맞다고 생각하는데 Solution에서 짠 대로 따라갔습니다. 😊

2024-09-09 08:09 UTC, Minjoo522 commented on backend/src/main/java/develup/domain/discussion/Discussion.java
> +
dto에서 어쩌면 비즈니스 로직일수도 있는 null, 빈 값 확인이 들어가는게 조금 걸리는데 어떻게 생각하시나요?

2024-09-09 08:11 UTC, Minjoo522 commented on backend/src/main/java/develup/application/discussion/DiscussionService.java
> +    }
우선 반영 했습니다!
Discussion을 생성할 때 HashTag가 없는 경우 저는 빈 배열을 받을 것 ➡️ 이 부분은 프론트와 소통이 필요하겠네요 😭

2024-09-09 08:11 UTC, Minjoo522 commented on backend/src/main/java/develup/application/discussion/DiscussionService.java
> +    }
오 감사합니다!
그런데 존재하지 않는 ID가 들어왔을 때 예외처리는 필요 없을까요...?

2024-09-09 08:13 UTC, le2sky commented on backend/src/main/java/develup/application/discussion/DiscussionService.java
> +    }
예외처리가 필요하다면, in 쿼리로 반환되는 List의 사이즈와 원본 ID 리스트의 수를 검증하면 어떨까요?

2024-09-09 09:58 UTC, alstn113 commented on backend/src/main/java/develup/domain/discussion/Discussion.java
> +
getMission, getMember 등등 null이 들어갈 수 있는 부분은 굉장히 많아요.
저희가 초반에 entity에서 null 체크를 하지 말자고 해서 이런 코멘트를 남겼어요.
이 정도면 괜찮을 것 같기도 하네요. 👍

2024-09-09 09:59 UTC, alstn113 approved these changes

2024-09-10 05:30 UTC, Minjoo522 commented on backend/src/main/java/develup/application/discussion/DiscussionService.java
> +    }
어떤 ID에서 문제가 발생했는지 명확히 할 필요까지는 없는 것 같아서 쿼리 수를 줄이는 게 훨씬 합리적인 것 같네요! 반영했습니다!

2024-09-10 05:34 UTC, Minjoo522 commented on backend/src/main/java/develup/domain/discussion/Discussion.java
> +
요청에서 빈 리스트가 들어올 것으로 예상하고 있기 때문에 예외처리는 제거했습니다!
추후 예외 처리 추가가 필요하다면 service 단에서 할 수 있는 방법이 있는지 더 고민할 수 있을 것 같아요. 👍

2024-09-10 07:02 UTC, le2sky approved these changes
고생하셨습니다!!

2024-09-10 07:41 UTC, merged