디스커션 목록 조회 기능 구현 (issue #439)
woowacourse-teams/2024-devel-up pull request #441
Opened 2024-09-09 06:57 UTC by lilychoibb

#### 구현 요약

전체 디스커션 목록 조회 기능 구현
commentCount 는 로빈이 작업중이라서 일단 하드코딩해서 값 넣어놨습니당

#### 연관 이슈

- close #439 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-09-09 07:47 UTC, le2sky approved these changes
고생 많으셨습니다! 말씀 드린 테스트랑 lower 처리 해주시면 좋을 것 같아요.👍

2024-09-09 07:52 UTC, alstn113 requested changes
빠르게 구현하느라 수고하셨습니다. 👍👍👍👍

수정 사항 코멘트로 남겼습니다.
추가적으로 repository, service 테스트도 해주시면 좋을 것 같아요!

2024-09-09 07:52 UTC, alstn113 commented on backend/src/main/java/develup/application/discussion/SummarizedDiscussionResponse.java
> +) {
[Request Changes]

commentCount -> int
String memberImgUrl은 MemberResponse로 바꾸면 좋을 것 같아요.
멤버를 클릭했을 경우 멤버 페이지로 이동할 수도 있어서 그렇습니다!

2024-09-09 07:52 UTC, alstn113 commented on backend/src/main/java/develup/api/DiscussionApi.java
> +            @RequestParam(defaultValue = "all") String missionTitle,
[Commnet]

개인적으로 missionTitle보다 mission이 좋을 것 같아요.

2024-09-09 07:52 UTC, alstn113 commented on backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
> +    );
[Request Changes]

all 이 ALL로도 들어올 수 있으니 mission repository와 같이 소문자로 변경하는 처리를 하면 좋을 것 같아요.

그리고 이 부분도 missionTitle이 아니라 String mission만으로도 충분히 이해가 가지 않을까 합니다.

2024-09-09 13:43 UTC, lilychoibb commented
@alstn113 @le2sky 
말씀주신 수정사항 반영했어요! 확인부탁드립니다 🤗😋

@Minjoo522 @robinjoon 
PR description 에 테스트 코드 에러와 관련해서 임시로 조치한 `@Transaction` 에 대해서 적어두었어요. 참고부탁드립니다 :)

2024-09-09 15:40 UTC, robinjoon commented
> @alstn113 @le2sky 말씀주신 수정사항 반영했어요! 확인부탁드립니다 🤗😋
> 
> @Minjoo522 @robinjoon PR description 에 테스트 코드 에러와 관련해서 임시로 조치한 `@Transaction` 에 대해서 적어두었어요. 참고부탁드립니다 :)

[슬랙 대화](https://devel-uphq.slack.com/archives/C07B285RDQV/p1725879060298419?thread_ts=1725871874.816249&cid=C07B285RDQV)에서 언급한 것 처럼, 표면적인 예외의 원인은 HashTag 객체가 이미 영속화 된 적이 있는 상태에서 영속성 컨텍스트가 종료되어 준영속 상태가 되고, 준영속 상태의 객체가 cascade 옵션에 의해 또 영속화가 시도되서 발생하는 예외에요. 트랜잭션을 걸면 영속성 컨텍스트가 테스트 메서드가 수행되는 동안 종료되지 않아, HashTag가 준영속 상태가 되지 않아서 문제가 발생하지 않는 것이구요.

2024-09-10 05:32 UTC, alstn113 approved these changes
수고하셨습니다 👍👍👍

2024-09-10 05:32 UTC, alstn113 commented on backend/src/test/java/develup/domain/discussion/DiscussionRepositoryTest.java
> +    @Transactional
👍👍👍

2024-09-10 05:32 UTC, alstn113 commented on backend/src/main/java/develup/application/discussion/SummarizedDiscussionResponse.java
> +        String mission,
[Commnet]

제가 생각하기에는 미션 이름은 태그 표시, 태그 필터링 용으로는 잘 사용될 것 같아요.
근데 제가 기대하는 기능은 미션 태그를 누를 때 미션 상세로 이동하는 것입니다. 
근데 어떻게 구현될 지 모르겠네요. 나중에 생각하죠!

2024-09-10 05:44 UTC, merged