디스커션 댓글 작성 및 조회 기능 구현 (issue #429)
woowacourse-teams/2024-devel-up pull request #445
Opened 2024-09-09 08:19 UTC by robinjoon

#### 구현 요약

디스커션 댓글 작성 및 조회 API를 구현합니다.

#### 연관 이슈

- close #429 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-09-09 08:26 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentResponse.java
> +) {
솔루션 댓글과 달리, 댓글과 답글을 같은 DTO로 응답합니다. parentID의 null 처리만 잘 해주면 클래스가 폭발하지 않고 문제가 잘 해결됩니다.

2024-09-09 08:30 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentService.java
> +    }
1. 디스커션 댓글 전체 조회
2. 디스커션 루트 댓글 조회
3. 디스커션 루트 댓글 기준으로 전체 댓글 그룹화
4. DTO 변환
순으로 진행됩니다.

루트 댓글을 판단할 때 삭제된 루트 댓글은 없어지므로, 이에 달린 답글은 그룹화 대상이 될 수 없습니다.

댓글을 DTO로 변환할 때 삭제된 댓글이면 마스킹하므로 결과적으로 삭제된 답글만 마스킹 됩니다.

2024-09-09 08:59 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentService.java
> +    }
1. 디스커션 댓글 전체 조회
2. 디스커션 루트 댓글 조회
3. 디스커션 루트 댓글 기준으로 전체 댓글 그룹화
4. 삭제되고 답글이 없는 것을 숨긴다.
5. DTO 변환
순으로 진행됩니다.

댓글을 DTO로 변환할 때 삭제된 댓글이면 마스킹하므로 결과적으로 삭제된 답글만 마스킹 됩니다.

2024-09-09 09:58 UTC, Minjoo522 requested changes
안녕하세요, 로빈 고생하셨습니다.
간단한 코멘트 남겼습니다.
필요하다고 생각하시는 부분 반영해주세요. 😊

2024-09-09 10:40 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentService.java
> +                .filter(DiscussionComment::isNotDeleted)
> [Request Changes] 루트 코멘트가 삭제되면 답글도 못 보게 되는 구조가 되는 것 같은데 맞을까요? 그렇다면 원래는 루트 코멘트가 삭제되어도 답글은 볼 수 있었던 걸로 기획했던 걸로 기억하는데 혹시 제 기억이 잘못 됐을까요?

이 부분 제가 잘못 이해해서 잘못 구현했었습니다... 수정해서 반영해놨어요! @Minjoo522

2024-09-09 10:41 UTC, robinjoon commented on backend/src/test/java/develup/support/data/DiscussionCommentTestData.java
> +        // private 생성자로 외부에서 직접 Builder를 생성하지 못하도록 함
> [Request Changes] 주석은 없어도 될 것 같습니다. 😊 아래도 동일합니다.

GPT의 흔적을 발견하셨군요... ㅋㅋㅋㅋㅋㅋ

2024-09-09 14:34 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentResponse.java
> +    }
> 혹시 이렇게 조기 리턴 하면 문제가 될까요? 아니면 `isNotDeleted`가 아닌 `isDelete`메서드를 사용하는 것도 직관적일 것 같습니다.

이 부분 요구사항 이해를 잘못하고 구현해서 발생한 문제였습니다. 수정하면서 같이 반영했습니다! https://github.com/woowacourse-teams/2024-devel-up/pull/445/commits/de235984eea7ffded49b00e91f26e4f23f4b4176

2024-09-09 14:35 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentResponse.java
> +    }
> 추가적으로 저는 삭제되었을 경우 content를 빈 값으로 보내주고 `isDeleted` 를 클라이언트 측에 제공함으로써 클라이언트 측에서 `isDeleted`를 확인하여 삭제되었을 경우 디스플레이 할 값을 직접 설정할 수 있도록 하는 걸 선호합니다.
> 
> 지금 같은 경우는 클라이언트 측에서 `if (data.content === "삭제된 댓글입니다.")` 로 확인해야 해서 불편할 것 같습니다.

말씀 주신 부분 일리가 있는 것 같습니다! 👍 이 부분은 프론트엔드 분들이랑 상의 후에 결정하겠습니다~

2024-09-09 14:37 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentResponse.java
> +        @Nullable
> [Comment] 지금까지 응답 객체에서는 `@Nullable` 따로 사용하지 않았던걸로 기억하는 데 문서화를 위해 사용하신 걸까요?

네 맞아요. 검증의 이유보다는 기존의 솔루션 댓글과 다른 구조로 먼저 만들고 각 구현에서 좋은 부분을 채용해서 서로 리팩토링하기로 했어서 두 구현에서 가장 크게 다른 이 부분을 명시했습니다.

2024-09-09 14:42 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentCreateRequest.java
> +public record DiscussionCommentCreateRequest(
반영했습니다! https://github.com/woowacourse-teams/2024-devel-up/pull/445/commits/bc2e4980b698bfdee52e8379e9c8296481d81f25

2024-09-09 14:43 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentService.java
> +                .orElse(null);
반영했습니다! https://github.com/woowacourse-teams/2024-devel-up/pull/445/commits/f5970b4d43b1619cf78997c39e110a1a8eac8b8d

2024-09-09 14:43 UTC, robinjoon commented on backend/src/test/java/develup/support/data/DiscussionCommentTestData.java
> +        // private 생성자로 외부에서 직접 Builder를 생성하지 못하도록 함
반영했습니다! https://github.com/woowacourse-teams/2024-devel-up/pull/445/commits/dfaf6ca6f18415470efc91951511b03d3b7075c0

2024-09-09 14:45 UTC, robinjoon commented
리브 남겨주신 코멘트 반영했고 반영한 커밋 각 코멘트에 답글로 달아두었습니다~

2024-09-09 16:37 UTC, Minjoo522 commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentResponse.java
> +    }
조기 리턴은 아직 반영되지 않는 것으로 보이는데 혹시 조기 리턴을 했을 때 발생하는 문제나 단점이 있을까요?

그리고 `isDeleted` 제공 여부는 이 커밋이 머지 되기 전에 상의가 되면 더 좋을 것 같습니다.
아마도 솔루션의 댓글, 답글과 같은 컴포넌트가 사용될 것 같은데 통일되지 않는다면 클라이언트 측에서도 번거로울 것 같아서요. 😊

2024-09-09 16:42 UTC, Minjoo522 requested changes
로빈 빠르게 반영해주셨네요.
반영해주신 부분에 대해 코멘트 추가로 남겼으니 확인 부탁 드립니다.
그리고 이 PR이 머지되기 전에 솔루션 댓글, 로빈이 작성한 디스커션 댓글 중 어떤 코드를 차용할 것인지 미리 합의를 했으면 좋겠다고 생각합니다. 다른 분들은 어떻게 생각하실지 모르겠네요. 😅

2024-09-09 16:42 UTC, Minjoo522 commented on backend/src/main/java/develup/api/DiscussionCommentApi.java
> +        var responses = discussionCommentService.getGroupingComments(discussionId);
이 부분은 다같이 논의가 필요할 것 같습니다.
어떤 부분에서는 var를 쓰고 어떤 부분에서는 사용하지 않는다면 자칫하면 통일성이 없어 보일 것 같습니다.

`길다`, `코드가 못생겨진다`도 상당히 주관적인 부분이라고 생각해서요. 😅

2024-09-09 16:42 UTC, Minjoo522 commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentResponse.java
> +    }
조기 리턴은 아직 반영되지 않는 것으로 보이는데 혹시 조기 리턴을 했을 때 발생하는 문제나 단점이 있을까요?

그리고 `isDeleted` 제공 여부는 이 PR이 머지 되기 전에 상의가 되면 더 좋을 것 같습니다.
아마도 솔루션의 댓글, 답글과 같은 컴포넌트가 사용될 것 같은데 통일되지 않는다면 클라이언트 측에서도 번거로울 것 같아서요. 😊

2024-09-10 01:34 UTC, robinjoon commented on backend/src/main/java/develup/api/DiscussionCommentApi.java
> +        var responses = discussionCommentService.getGroupingComments(discussionId);
릴리한테 물어보니 var 안쓰기로 했다네요. 반영했습니다. https://github.com/woowacourse-teams/2024-devel-up/pull/445/commits/e1185b24d8470e6ae2b67aefa44856f1474bac57 https://github.com/woowacourse-teams/2024-devel-up/pull/445/commits/d9f4315edfc53ff4f22d102fc2464305af69bd5f

2024-09-10 05:43 UTC, Minjoo522 requested changes
로빈 추가적으로 컨벤션 관련해서 확인 필요한 게 있어서 더 남겨둡니다. 확인 부탁드려요.

2024-09-10 05:43 UTC, Minjoo522 commented on backend/src/main/java/develup/api/DiscussionCommentApi.java
> +        return ResponseEntity.ok(new ApiResponse<>(discussionCommentService.getGroupingComments(discussionId)));
[Request Changes]
```suggestion
List<GroupingDiscussionCommentResponse>> responses = discussionCommentService.getGroupingComments(discussionId);

return ResponseEntity.ok(new ApiResponse<>(responses));
```

한 줄이라도 변수로 분리하는 컨벤션입니다.
가급적 이런 컨벤션은 맞춰주시는 게 좋을 것 같습니다. 😊

2024-09-10 05:43 UTC, Minjoo522 commented on backend/src/main/java/develup/api/DiscussionCommentApi.java
>          return ResponseEntity.ok(new ApiResponse<>(response));
[Request Changes]
```suggestion
        DiscussionCommentResponse response = discussionCommentService.createComment(
                accessor.id(),
                discussionId,
                commentCreateRequest
        );

        return ResponseEntity.ok(new ApiResponse<>(response));
```

리턴 전 한 줄 띄우는 것도 컨벤션이었던 걸로 알고 있습니다. 😊

2024-09-10 07:19 UTC, closed without merging