디스커션 조회 기능 구현 (issue #442)
woowacourse-teams/2024-devel-up pull request #450
Opened 2024-09-10 08:20 UTC by lilychoibb

#### 구현 요약

디스커션 피드 상세 조회 기능을 구현합니다.

### DiscussionResponse 예시
```
{
  "data": {
    "id": 1,
    "title": "객체지향이 뭘까요?",
    "content": "객체지향에 대해 토론해봅시다.",
    "mission": {
      "id": 1,
      "title": "주문",
      "thumbnail": "https://raw.githubusercontent.com/develup-mission/docs/main/image/java-order.png",
      "summary": "배달 주문을 받아보자",
      "url": "https://github.com/develup-mission/java-order",
      "hashTags": [
        {
          "id": 1,
          "name": "JAVA"
        },
        {
          "id": 2,
          "name": "객체지향"
        },
        {
          "id": 3,
          "name": "클린코드"
        }
      ]
    },
    "member": {
      "id": 1,
      "email": "test1@gmail.com",
      "name": "구름",
      "imageUrl": "https://avatars.githubusercontent.com/u/75781414?v=4"
    },
    "hashTags": [
      {
        "id": 1,
        "name": "JAVA"
      },
      {
        "id": 2,
        "name": "객체지향"
      },
      {
        "id": 3,
        "name": "클린코드"
      }
    ]
  }
}
```

#### 연관 이슈

- close #442 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-09-11 14:23 UTC, robinjoon approved these changes
안녕하세요 릴리! 다른 디스커션 관련 기능에서 거의 만들어진 부분에 대한 단순 구현이라서 특별히 리뷰 남길 부분이 없네요. 👍

2024-09-12 01:30 UTC, le2sky requested changes
릴리 안녕하세요. 아톰입니다. 잘 구현 해주셨네요.  👍
discussion 단건 조회와 solution 단건 조회에서 추가 쿼리가 발생해요.
릴리의 의견이 궁금하여 RC 남깁니다. 위에서 발생하는 추가 쿼리를 막는게 나을까요?

2024-09-12 01:52 UTC, lilychoibb commented
추가 쿼리 나가는 거 해결해보겠습니다 ☺️! 
이 PR 에 추가 push 해놓을게요

2024-09-17 10:11 UTC, lilychoibb commented
@le2sky 이전에 조회 쿼리 8개(😇) 나가는 것 해결해두었습니다.
```
select
        d1_0.id,
        d1_0.content,
        d1_0.created_at,
        ht2_0.discussion_id,
        ht2_0.hash_tag_id,
        ht3_0.id,
        ht3_0.name,
        d1_0.member_id,
        m2_0.id,
        m2_0.created_at,
        m2_0.email,
        m2_0.image_url,
        m2_0.name,
        m2_0.provider,
        m2_0.social_id,
        m1_0.id,
        ht1_0.mission_id,
        ht1_0.id,
        ht1_0.hash_tag_id,
        m1_0.url,
        m1_0.summary,
        m1_0.thumbnail,
        m1_0.title,
        d1_0.title 
    from
        discussion d1_0 
    join
        mission m1_0 
            on m1_0.id=d1_0.mission_id 
    join
        mission_hash_tag ht1_0 
            on m1_0.id=ht1_0.mission_id 
    join
        member m2_0 
            on m2_0.id=d1_0.member_id 
    join
        discussion_hash_tag ht2_0 
            on d1_0.id=ht2_0.discussion_id 
    join
        hash_tag ht3_0 
            on ht3_0.id=ht2_0.hash_tag_id 
    where
        d1_0.id=? 
    order by
        ht2_0.discussion_id,
        ht2_0.hash_tag_id,
        ht1_0.id

2024-09-18 04:10 UTC, le2sky approved these changes
릴리 연휴인데 고생 많으셨어요. 👍👍👍

2024-09-19 01:26 UTC, merged