요청 및 응답 로깅 구현(issue #448)
woowacourse-teams/2024-devel-up pull request #459
Opened 2024-09-12 04:08 UTC by robinjoon

#### 구현 요약

HTTP 요청과 응답을 로그로 남기고 이를 추적하기 위한 식별자인 TraceId 를 응답의 헤더 `Trace-Id `로 지정했습니다.

이를 통해 QA 혹은 기타 테스트 상황에서 예상하지 못한 동작이 발생할 경우, 이를 추적하기 수월해집니다. 

추가로 기존에 Loki에 전송되는 로그 포맷과 로컬에서 터미널에 출력되는 로그의 형식이 다른 것을 로컬의 형식으로 통일했습니다.

아래는 이를 적용했을 시 남겨지는 로그입니다.

![image](https://github.com/user-attachments/assets/bb811389-ecca-4dcd-b4b4-d58afbb083a5)

아래는 curl 을 통한 요청 시 응답의 헤더를 포함한 출력 예시입니다.

![image](https://github.com/user-attachments/assets/3700757d-5223-4528-9b35-9e8ba2d95163)

#### 연관 이슈

이 부분을 제거하고 연관된 이슈를 아래와 같이 명시해 닫아주세요.

> ex) close #12

#### 참고

메인 서버 배포 후 Loki 등에서 잘 수집하는지 확인할 필요가 있습니다.

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-09-12 14:55 UTC, robinjoon commented on backend/src/main/java/develup/api/logging/LoggingFilter.java
> +        MDC.put("traceId", header);
Nginx를 사용하면 그 로그도 남겨야 하는데, Nginx에서 리버스 프록시를 수행할 때  X-Request-ID라는 헤더를 추가할 수 있습니다. Nginx 로그에 X-Request-ID가 사용되므로 이와 같은 식별자를 사용할 수 있게 하기 위한 구현입니다. 개발 서버에서는 여전히 Nginx를 사용할 것이라 생각해 남겨두었습니다.

2024-09-13 01:27 UTC, le2sky requested changes
로빈 안녕하세요. 아톰입니다.
고생 많으셨어요. 커멘트 남겼으니 시간 남으실때 확인 부탁드려요.
그리고, 해당 작업을 해서 얻을 수 있는 이점을 PR 본문에 추가해주면 도움이 될 것 같아요.👍

2024-09-13 01:27 UTC, le2sky commented on backend/src/main/java/develup/api/logging/LoggingFilter.java
> +                {} {}?{}
[Request Changes]

localhost:8080/solutions?null

이런 형식으로 나오는 것을 개선할 수 있을까요?

2024-09-13 07:37 UTC, robinjoon commented on backend/src/main/java/develup/api/logging/LoggingFilter.java
> +                {} {}?{}
> [Request Changes]
> 
> localhost:8080/solutions?null
> 
> 이런 형식으로 나오는 것을 개선할 수 있을까요?

쿼리가 없을 경우 `localhost:8080/solutions`로 나오게 하자는 말씀이시죠? 알겠습니다!

2024-09-14 02:55 UTC, alstn113 approved these changes
로그 개선하느라 수고하셨습니다. 👍👍
중요한 부분은 아니고 참고할만한 부분 적어놨습니다.

2024-09-14 02:55 UTC, alstn113 commented on backend/src/main/resources/logback-spring.xml
[Approve]

traceId 부분에서 대괄호는 다른 부분과 일관성을 위해서 빼는게 보기 편할 것 같아요.
그리고 시간을 더 빨리 볼 것 같은데 시간을 제일 앞으로 이동하는건 어떤가요?

2024-09-14 02:55 UTC, alstn113 commented on backend/src/main/resources/logback-spring.xml
> +                    %highlight(%-5p) | %cyan(%logger{36}) | %m%n
[Commnet]

이 부분에서 줄바꿈이 로그로 기록될 때도 줄바꿈이 되는 것 같아요. 참고 부탁드립니다.

2024-09-18 06:53 UTC, robinjoon commented on backend/src/main/resources/logback-spring.xml
> +                    %highlight(%-5p) | %cyan(%logger{36}) | %m%n
무슨 말인지 잘 모르겠어요!

2024-09-18 06:56 UTC, alstn113 commented on backend/src/main/resources/logback-spring.xml
> +                    %highlight(%-5p) | %cyan(%logger{36}) | %m%n
@robinjoon  수정하다보니 잘못 적은 것 같아요! 다시 적었습니다. ㅋㅋ

2024-09-18 06:57 UTC, robinjoon commented on backend/src/main/resources/logback-spring.xml
반영했어요. https://github.com/woowacourse-teams/2024-devel-up/pull/459/commits/aeaf39775671a9c0704e68ee798cd998c3413826

2024-09-18 06:58 UTC, robinjoon commented on backend/src/main/java/develup/api/logging/LoggingFilter.java
> +    }
아예 JSON 데이터는 이쁘게 출력하도록 변경했어요. https://github.com/woowacourse-teams/2024-devel-up/pull/459/commits/f68e95b521d7551a8267f5acf8331da99bd6ddf9

2024-09-18 06:58 UTC, robinjoon commented on backend/src/main/java/develup/api/logging/LoggingFilter.java
> +                {} {}?{}
반영했어요. https://github.com/woowacourse-teams/2024-devel-up/pull/459/commits/e1e60fa71fed7776e7ea9f61bd6b2e1a0198d619

2024-09-18 06:59 UTC, robinjoon commented on backend/src/main/java/develup/api/logging/LoggingFilter.java
> +    private void addTraceIdToRespone(HttpServletResponse response) {
반영 했어요. https://github.com/woowacourse-teams/2024-devel-up/pull/459/commits/de96f2ee66db38dba260935d10d24900745517f9

2024-09-18 07:06 UTC, robinjoon commented on backend/src/main/resources/logback-spring.xml
> +                    %highlight(%-5p) | %cyan(%logger{36}) | %m%n
아 인텔리제이가 지 맘대로 계속 바꾸네요.. 수정해서 올릴게요

2024-09-18 07:16 UTC, alstn113 approved these changes

2024-09-19 15:03 UTC, robinjoon commented
뭐여 이거 PR 왜 이케 됨..?

2024-09-20 01:32 UTC, le2sky approved these changes
고생하셨어요 로빈 👍

2024-09-20 01:33 UTC, merged