OAuth 인증 코드 확장성 개선 (issue #444)
woowacourse-teams/2024-devel-up pull request #476
Opened 2024-09-16 08:47 UTC by alstn113

#### 구현 요약

oauth에 대한 확장성을 고려해 추상화를 했습니다.

다음의 디자인 패턴이 적용됐습니다.
- 전략 패턴 (Strategy)
- 전략 패턴을 적용하는 Context
- map으로 Strategy를 모아놓은 레지스트리 패턴 (Registry)

controller에서 OAuthProviderConverter를 적용했습니다.
open-session-in-view가 켜져있어서 의미는 없겠지만 외부 요청을 트랜잭션에서 빼서 처리했습니다.
RestClientTest를 통해서 mock server를 이용해 외부 API를 테스트했습니다.

#### 연관 이슈

- https://github.com/woowacourse-teams/2024-devel-up/issues/443
- close #444 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-09-16 08:50 UTC, alstn113 commented on backend/src/test/java/develup/infra/auth/oauth/github/GithubOAuthClientTest.java
> +    private MockRestServiceServer mockServer;
RestClientTest를 이용해서 mock server를 만들어서 테스트했습니다.

2024-09-16 08:51 UTC, alstn113 commented on backend/src/main/java/develup/api/auth/OAuthProviderConverter.java
> +}
PathVariable에서 OAuthProvider를 인자로 받기 때문에 
String -> OAuthProvider로 변경해주는 컨버터입니다.

2024-09-16 08:53 UTC, alstn113 commented on backend/src/main/java/develup/application/auth/oauth/OAuthStrategy.java
> +}
GithubOAuthStrategy, GoogleOAuthStrategy, KakaoOAuthStrategy 등등이 될 수 있는 인터페이스입니다. 
OAuthStrategyRegistry에서 Set<OAuthStrategy>로 의존성 주입을 받습니다.

2024-09-16 08:54 UTC, alstn113 commented on backend/src/main/java/develup/application/auth/oauth/OAuthContext.java
> +}
OAuthProvider를 통해서 OAuthStrategy를 찾고 실행하는 Context입니다.

2024-09-16 08:55 UTC, alstn113 commented on backend/src/test/java/develup/api/ApiTestSupport.java
테스트에서 OAuthProviderConverter를 MockBean으로 하면 이상하게 예외가 발생하더라구요.
그래서 존재하지 않습니다.

2024-09-18 04:00 UTC, le2sky requested changes
구름 안녕하세요. 아톰입니다. 사정이 있어 리뷰가 늦어진 점 죄송합니다. 🥲 
OAuth 인증 코드 확장성있게 잘 개선해주셨네요. 이런 PR은 개선 라벨과 refactor 브랜치로 작성해주는 것은 어떨까요?

그리고 최근에 알게된 부분인데요. OSIV가 켜져있다고 해도 EntityManager 사용 시점이나 트랜잭션  AOP 프록시 호출 이전까지는 스레드가 커넥션을 점유하지 않더라구요? 예를 들어, 구름이 작성하신 부분에 다음과 같이 데이터소스 로그 찍어보면, 외부 API 호출 이후에 커넥션을 점유합니다. 유의미하게 잘 개선해주셨네요. 👍 (이전에는 외부 API 호출 이전에 커넥션을 점유하는 걸로 보입니다.)

```java
   public String oauthLogin(OAuthProvider provider, String code) {
        HikariPoolMXBean hikariPoolMXBean = hikariDataSource.getHikariPoolMXBean();
        logger.info("user 정보 불러오기 이전 활성 커넥션 = {}", hikariPoolMXBean.getActiveConnections());
        OAuthUserInfo userInfo = oauthContext.getOAuthUserInfo(provider, code);
        logger.info("user 정보 불러오기 이후 활성 커넥션 = {}", hikariPoolMXBean.getActiveConnections());

        MemberResponse memberResponse = memberService.findOrCreateMember(userInfo, provider);
        logger.info("em 호출 및 트랜잭션 aop 프록시 호출 이후 시점 활성 커넥션 = {}", hikariPoolMXBean.getActiveConnections());

        return tokenProvider.createToken(memberResponse.id().toString());
    }
```

```
2024-09-18T12:52:19.390+09:00  INFO 49944 --- [devel-up] [nio-8080-exec-3] d.application.auth.oauth.OAuthService    : user 정보 불러오기 이전 활성 커넥션 = 0
2024-09-18T12:52:20.316+09:00  INFO 49944 --- [devel-up] [nio-8080-exec-3] d.application.auth.oauth.OAuthService    : user 정보 불러오기 이후 활성 커넥션 = 0
2024-09-18T12:52:20.409+09:00  INFO 49944 --- [devel-up] [nio-8080-exec-3] d.application.auth.oauth.OAuthService    : em 호출 및 트랜잭션 aop 프록시 호출 이후 시점 활성 커넥션 = 1
```

2024-09-18 04:01 UTC, le2sky commented
++ 그런데 이제 AuthService는 무슨 역할을 수행하는건가요?

2024-09-18 06:23 UTC, robinjoon requested changes
구름 구조 잘 짜주셨네요. 몇가지 네이밍 관련 코멘트 남겨놨으니 확인해주세요~

2024-09-18 06:23 UTC, robinjoon commented on backend/src/main/java/develup/application/auth/oauth/OAuthStrategyRegistry.java
> +    public OAuthStrategyRegistry(Set<OAuthStrategy> providers) {
[Request Change]

매개변수의 타입은 전략인데, 변수 이름은 제공자인 부분이 헷갈리게 하네요.

2024-09-18 06:23 UTC, robinjoon commented on backend/src/main/java/develup/application/auth/oauth/OAuthStrategyRegistry.java
> +    }
[Request Change] 

여기도 비슷하게 반환 타입이랑 메서드 이름이 불일치 하네요.

2024-09-18 06:23 UTC, robinjoon commented on backend/src/test/java/develup/infra/auth/oauth/github/GithubOAuthClientTest.java
> +        });
[Comment]

우리 assertAll만 쓰기로 했던 것 같아요. 아닌가요??🤔

2024-09-18 07:02 UTC, alstn113 commented on backend/src/main/java/develup/api/AuthApi.java
>      @Operation(summary = "깃허브 인증 API", description = "깃허브 로그인 페이지로 리다이렉트합니다.")
https://github.com/woowacourse-teams/2024-devel-up/pull/476/commits/4a55e825b11fbe8d3486022da56fcfcb77e2e1fb

놓쳤던 부분이네요. 수정했습니다.

2024-09-18 07:34 UTC, alstn113 commented on backend/src/test/java/develup/application/auth/oauth/OAuthServiceTest.java
> +    private OAuthContext oAuthContext;
https://github.com/woowacourse-teams/2024-devel-up/pull/476/commits/aa97eed80d7c0b076aea37ee22d3e4fd77f7b1f3

AutoConfigureMockMvc 이 친구 제거하고, MockBean IntegrationTestSupport로 이동했어요. 
Context 새로 생기지 않네요 👍

2024-09-18 07:48 UTC, alstn113 commented on backend/src/main/java/develup/application/auth/oauth/OAuthStrategyRegistry.java
> +    public OAuthStrategyRegistry(Set<OAuthStrategy> providers) {
https://github.com/woowacourse-teams/2024-devel-up/pull/476/commits/fbfaa68d3db9fba997ff2353db7d2ab5a14cc1d0

있는 거 붙여넣고 자꾸 바꾸다보니 놓쳤네요. 수정했습니다!

2024-09-18 07:49 UTC, alstn113 commented on backend/src/main/java/develup/application/auth/oauth/OAuthStrategyRegistry.java
> +    }
https://github.com/woowacourse-teams/2024-devel-up/pull/476/commits/58d692ba4ebc0fc9089b549af17d1cddaa8308ac

수정했습니다!

2024-09-18 07:50 UTC, alstn113 commented on backend/src/test/java/develup/infra/auth/oauth/github/GithubOAuthClientTest.java
> +        });
미션하다보니 컨벤션을 헷갈렸네요. 수정했습니다!

2024-09-18 07:52 UTC, alstn113 commented
> ++ 그런데 이제 AuthService는 무슨 역할을 수행하는건가요?

TokenProvider를 api 쪽에서 바로 쓰고 싶지 않아서요. 
휴가 보내겠습니다. 😅

2024-09-21 09:30 UTC, robinjoon approved these changes
제가 이야기한 부분 모두 반영된 것 확인했습니다! 수고하셨어요!

2024-09-23 08:55 UTC, alstn113 commented on backend/src/test/java/develup/infra/auth/oauth/github/GithubOAuthClientTest.java
> +    private MockRestServiceServer mockServer;
Connection Timeout은 서버와 연결을 시도하는 시간의 제한입니다.
Read Timeout은 연결 후 응답을 기다리는 시간의 제한입니다.

각각을 5초, 5초로 할려다가 응답은 지연될 수 있으므로 10초로 변경했습니다.

2024-09-24 00:52 UTC, le2sky approved these changes
👍👍 고생 많으셨습니다!

2024-09-24 01:42 UTC, merged