무중단 배포 스크립크 작성 (issue #456)
woowacourse-teams/2024-devel-up pull request #480
Opened 2024-09-19 15:24 UTC by robinjoon

#### 구현 요약

Rolling 방식의 무중단 배포를 구현했습니다.

알림은 4가지 시나리오에서 발생합니다.

1. [둘 다 성공](https://github.com/woowacourse-teams/2024-devel-up/actions/runs/10937753254)
2. A 성공 B 실패
3. [A 실패 롤백 성공](https://github.com/woowacourse-teams/2024-devel-up/actions/runs/10938693881)
4. [A 실패 롤백 실패](https://github.com/woowacourse-teams/2024-devel-up/actions/runs/10937696286)

두번째 시나리오는 극단적인 상황이라 재현이 힘들어서 따로 테스트하지 못했습니다.

#### 연관 이슈

- close #456

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-09-19 15:26 UTC, robinjoon commented
기존 PR 닫고 커밋들만 체리 픽 해서 새로 PR 만들었어요 @alstn113

2024-09-21 03:03 UTC, le2sky requested changes
안녕하세요. 아톰입니다. 구현 잘해주시고 시나리오 별로 테스트 결과 공유 해주셔서 감사합니다.
엣지 케이스가 될만한 부분 의견 들어보고 싶어서 RC 드려요. 고생 많으셨습니다. 😀

2024-09-21 03:03 UTC, le2sky commented on .github/workflows/backend_cd.yml
> +          echo $PREVIOUS_IMAGE_NAME
[Commnet]

build job이 해당 작업 안기다려줘도 되는건지 궁금하네요. 👀
만약, build job -> deployToA job까지 수행 했어요.
그리고 healthCheckA 수행 이전에 컨테이너가 잠깐 실행되었고 실패했다고 했을때, docks ps를 찍으면 실패한 최신 도커 이미지 버전이 롤백 대상 버전이 될 가능성은 없나요??

2024-09-21 03:14 UTC, robinjoon commented on .github/workflows/backend_cd.yml
> +          echo $PREVIOUS_IMAGE_NAME
![image](https://github.com/user-attachments/assets/4ac53353-4343-431a-9615-040cc38554b8)
그런 시나리오가 원천적으로 불가능한 건 아니라고 생각해요. 그런데, 현실적으로 빌드 작업과 롤백 버전 찾는 작업이 동시에 트리거되면 그 작업의 부하 차이가 워낙 커서 롤백 버전 찾는 작업이 먼저 수행되게 되요. 위에 사진 보시면 속도 차이가 엄청 나요

2024-09-21 03:20 UTC, le2sky commented on .github/workflows/backend_cd.yml
> +          echo $PREVIOUS_IMAGE_NAME
굳굳 좋아요. 그럴 가능성이 적긴하네요. 👍
cd 과정에 평균 find previus docker image version 잡 수행 시간이 추가되는 것보다는 자동 롤백 실패 비용이 더 작겠네요.
graceful shutdown 논의는 슬랙으로 이어나가시고, 헬스 체크 api 선택적으로 반영해주시고 다시 요청 주시면 approve 처리할게요.

2024-09-22 07:48 UTC, Minjoo522 reviewed
로빈 안녕하세요 고생하셨습니다.
다른 부분은 아톰이 리뷰 주신 부분 외에 크게 변경할 부분 없는 것 같네요.
다만 네이밍 컨벤션을 지금까지는 kebab-case 또는 snake_case를 사용했는데,  이는 기존에 깃허브 액션에서 주어진 옵션들이 전부 kebab-case 또는 snake_case를 사용해서 작성되었기 때문이에요. (ex. runs-on)

저는 좀 통일성 있게 가져가는 게 좋다고 생각하는데 다른 분들 의견은 어떨지 궁금하네요.

2024-09-23 07:15 UTC, robinjoon commented on backend/src/main/java/develup/api/HealthApi.java
> +    }
반영했어요 https://github.com/woowacourse-teams/2024-devel-up/pull/480/commits/0c0101ed8e8a85549a44c40afbb40989515ed2fe

2024-09-23 07:19 UTC, le2sky approved these changes
고생 많으셨습니다!

2024-09-23 07:22 UTC, robinjoon commented
> 6b3bd18

case 변경했습니다. https://github.com/woowacourse-teams/2024-devel-up/pull/480/commits/6b3bd183ba0e0b3f36a7f66f9b5043519eb83aae

2024-09-23 12:36 UTC, Minjoo522 approved these changes
변경 확인 했습니다~

2024-09-23 12:45 UTC, lilychoibb approved these changes
로빈 고생많으셨습니다👍 
모르는 부분 질문 많이 했는데 설명 잘해주셔서 감사합니다!~

2024-09-23 12:46 UTC, merged