디스커션 수정 기능 구현 (issue #472)
woowacourse-teams/2024-devel-up pull request #492
Opened 2024-09-22 17:48 UTC by Minjoo522

#### 구현 요약

수정을 구현하며 고려한 부분은 수정 해야할 포인트가 여러 군데인데,
Mission과 HashTag의 경우 id로 비교해서 같은 경우 굳이 업데이트 될 필요가 없다고 생각했습니다.
비교하지 않고 바로 업데이트하면 로직이 편해지긴 하지만 DB 조회가 필요하기 때문입니다.
이 부분이 불필요하다고 생각하면 알려주세요.

그리고 영속성 문제로 테스트 메서드에 `@Transactional`을 붙여주지 않으면 Discussion 생성 과정에서 테스트가 실패합니다.
(이 부분은 이전에도 논의가 나왔었던 것 같아요 하지만 잘 기억나지 않아서 다시 언급합니다. ^^;;)
`DiscussionHashTags`의 `cascade = CascadeType.PERSIST`를 없애주면 해결이 되는데 이걸 유지하고 테스트 메서드에 `@Transactional`을 다는게 나을지 `cascade = CascadeType.PERSIST`을 없앨 다른 방법을 찾는게 나을지 논의해보았으면 합니다.

그리고 수정 시 `findFetchById` 메서드로 Discussion을 찾으려고 시도하면 조회가 안됩니다. 😅
우선 `findById`를 사용하도록 해두었는데 어느 부분이 문제인지 정확하게 찾을 수 없어서 같이 논의해보았으면 합니다!

#### 연관 이슈

- close #472

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-09-23 09:10 UTC, robinjoon requested changes
안녕하세요 리브! 수고 많았습니다! 아까 회의에서도 말씀주시고 코멘트에도 남겨주신 

> 그리고 수정 시 findFetchById 메서드로 Discussion을 찾으려고 시도하면 조회가 안됩니다. 😅
> 우선 findById를 사용하도록 해두었는데 어느 부분이 문제인지 정확하게 찾을 수 없어서 같이 논의해보았으면 합니다!

이 문제 해결하신거 확인하고 싶어서 RC로 남겨요!

2024-09-23 09:10 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/DiscussionService.java
>      }
[Approve]

이렇게 확인하는 로직이 추가된 건 좋은 거 같아요~

2024-10-04 06:02 UTC, robinjoon approved these changes

2024-10-04 06:40 UTC, le2sky approved these changes
고생하셨습니다. 👍👍

2024-10-04 06:42 UTC, lilychoibb approved these changes
리브 고생많으셨습니다! 👍 미션이랑 해시태그도 수정이 가능하군요 ㅎㅎ

2024-10-04 07:38 UTC, alstn113 approved these changes
수고하셨습니다~ 테스트가 많아서 믿음이 가네요

2024-10-04 07:39 UTC, merged