미션 제출 기능 구현 (issue#29)
woowacourse-teams/2024-devel-up pull request #50
Opened 2024-07-17 08:50 UTC by Minjoo522

#### 구현 요약

클라이언트로부터 미션 제출 관련 POST 요청을 받으면 DB에 관련 데이터를 저장하고 클라이언트에게 응답하는 기능을 구현했습니다.

- 추후 resolver를 통해 Member 객체 생성 예정으로 Controller에서 매개변수에 Member를 명시하지 않고 임시 데이터를 사용했습니다.
```java
    @PostMapping("/submissions")
    public ResponseEntity<ApiResponse<SubmissionResponse>> postSubmission(@RequestBody CreateSubmissionRequest request) {
        Member member = new Member(1L);
        SubmissionResponse newSubmission = submissionService.submit(member, request);
        return ResponseEntity.created(URI.create("/submissions/" + newSubmission.id()))
                .body(new ApiResponse<>(newSubmission));
    }
```

- MemberRepository 생성 전이라 테스트 코드에서 직접 Member 객체를 생성했습니다.
```java
    @Test
    @DisplayName("미션을 제출한다.")
    void createSubmission() {
        Member member = new Member(1L);
```

#### 연관 이슈

close #29

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-07-17 10:16 UTC, alstn113 requested changes
너무너무 수고 많으셨습니다!
수정할 부분에 대해서 리뷰 남겼습니다. 
앞으로도 파이팅입니다!!! 😊

2024-07-17 10:16 UTC, alstn113 commented on backend/src/main/java/develup/submission/CreateSubmissionRequest.java
> +    }
[Comment]

현재 dto들은 Entity와 1대1 대응인 상태라 상관이 없지만 
나중에 dto 하나에서 여러 엔티티로 갈 수도 있다고 생각해요. 😊

그래서 저는 보통 to{Entity} 즉, toSubmission 이런 식으로 사용해요.
저희가 아직 이 컨벤션을 정하지 않은 것 같은데 이 방식은 어떻게 생각하시나요? 🤫

2024-07-17 10:16 UTC, alstn113 commented on backend/src/main/java/develup/submission/SubmissionApi.java
> +    public ResponseEntity<ApiResponse<SubmissionResponse>> postSubmission(@RequestBody CreateSubmissionRequest request) {
postSubmission이 조금 어색한 것 같은데 대안을 모르겠네요 🤣,,,

2024-07-17 10:16 UTC, alstn113 commented on backend/src/main/java/develup/submission/SubmissionApi.java
> +        SubmissionResponse newSubmission = submissionService.submit(member, request);
[Comment]

newSubmission은 entity를 의미하는 것 같아서 submissionResponse나 response가 어떨까요? 🤫
 
```suggestion
        SubmissionResponse submissionResponse = submissionService.submit(member, request);
```

2024-07-17 10:16 UTC, alstn113 commented on backend/src/main/java/develup/submission/SubmissionResponse.java
> +    public static SubmissionResponse of(Submission submission) {
[Request Changes]

파라미터가 1개라서 of보다 from이 적합할 것 같아요 😄

```suggestion
    public static SubmissionResponse from(Submission submission) {
```

2024-07-17 10:16 UTC, alstn113 commented on backend/src/main/java/develup/submission/SubmissionService.java
> +@Transactional
`@Transactional`을 최상단에 다는건지 메서드마다 다는건지 정했던 것 같은데
문서를 찾아보니까 나오지 않네요,,, 🥲

2024-07-17 10:30 UTC, le2sky approved these changes
리브 안녕하세요. 아톰입니다.
금방 구현해주셨는데도 불구하고 좋은 코드 작성해주셨네요.
앞서 구름이 좋은 피드백 남겨주셔서 사소한 피드백 남깁니다.
시간 나실 때 살펴봐 주세요. 🙇🏻‍♂️

2024-07-17 10:30 UTC, le2sky commented on backend/src/main/java/develup/submission/SubmissionService.java
> +class SubmissionService {
접근자도 세심하게 잘 작성해주셨네요. 👍

2024-07-17 10:30 UTC, le2sky commented on backend/src/main/java/develup/submission/SubmissionResponse.java
> +                submission.getMission().getId(),
[Approve]

getter 연속 호출은 가독성을 낮춘다고 생각했어요.
아래와 같은 느낌은 어떨까요? 리뷰의 의견을 자유롭게 공유해주세요.

```suggestion
                submission.getMemberId(),
                submission.getMissionId(),
```

2024-07-17 10:30 UTC, le2sky commented on backend/src/main/java/develup/submission/SubmissionService.java
> +        return SubmissionResponse.of(newSubmission);
[Approve]

24번과 25번 라인 사이에 개행을 하면 더욱 보기 편할 것 같아요.
(제가 반환문 이전에 개행하는 습관이 있어서 그럴 수도 있어요.)

2024-07-17 10:43 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/CreateSubmissionRequest.java
> +    }
이 부분에 대해서 컨벤션을 따로 정하지 않았어서 아톰과 얘기하면서 결정했습니다.
아톰도 저도 둘 다 상관 없다고 생각하는 편이라 toEntity로 했는데 구름의 코멘트를 보니 toSubmission이 더 적합할 것 같네요!
반영했습니다. 😊

2024-07-17 10:46 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/SubmissionApi.java
> +    public ResponseEntity<ApiResponse<SubmissionResponse>> postSubmission(@RequestBody CreateSubmissionRequest request) {
제가 생각하기에도 100% 만족스럽지는 않은데 어떤 네이밍이 더 좋을지 고민입니다.
함께 Mission get 메서드를 만들 때 `getMission`과 같은 식으로 만들어서 `postSubmission`으로 했습니다. 😅
고민했던 후보는 `createSubmission`인데 어떤게 더 나을까요 😭

2024-07-17 10:46 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/SubmissionApi.java
> +        SubmissionResponse newSubmission = submissionService.submit(member, request);
response 좋네요! 반영했습니다. 😊

2024-07-17 10:48 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/SubmissionResponse.java
> +    public static SubmissionResponse of(Submission submission) {
실수했네요 😅
찾아줘서 고마워요!

2024-07-17 10:54 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/SubmissionService.java
> +@Transactional
저도 잘 기억이 안나서...
현재는 메서드가 하나밖에 없는데 혹시 @le2sky 아톰 기억 나시나요...?
댓글 부탁해요. 🙏

2024-07-17 10:55 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/SubmissionResponse.java
> +                submission.getMission().getId(),
전 둘 다 상관 없다파여서 아톰의 의견 반영했습니다! 😆

2024-07-17 10:56 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/SubmissionService.java
> +        return SubmissionResponse.of(newSubmission);
그러면 `submissionApi`의 `postSubmission`도 개행하는 게 좋을까요?
알려주시면 같이 반영하겠습니다!

2024-07-17 10:57 UTC, Minjoo522 commented
구름, 아톰!
코멘트 주신 내용 반영했습니다. 😊

2024-07-17 11:01 UTC, le2sky commented on backend/src/main/java/develup/submission/SubmissionService.java
> +@Transactional
코드 리뷰 시점에 의견 나눠보기로 했던 것으로 기억해요.
저는 메서드 레벨에서 누락되는 것을 방지하기 위해서 상단에 트랜잭션 어노테이션을 붙이는 것을 선호해요.
최상단이 readonly냐 아니냐는 서비스 클래스를 어떻게 나누는지에 따라서 달라질 수 있는 부분이라고 생각합니다.
당장은 상단에 어노테이션을 붙이는 것에만 초점을 맞춰서 다른 분들의 의견도 궁금해요.

2024-07-17 11:01 UTC, alstn113 commented on backend/src/main/java/develup/submission/SubmissionApi.java
> +    public ResponseEntity<ApiResponse<SubmissionResponse>> postSubmission(@RequestBody CreateSubmissionRequest request) {
makeSubmission은 어떨까요? 사실 상관없습니다 하하

2024-07-17 11:02 UTC, alstn113 approved these changes

2024-07-17 11:03 UTC, le2sky commented on backend/src/main/java/develup/submission/SubmissionService.java
> +        return SubmissionResponse.of(newSubmission);
개행에 대한 취향은 다른 분들 의견도 들어보고 싶어서요.
일단은 반영하지 않는게 좋을것 같아요!

2024-07-17 11:05 UTC, alstn113 commented
RCA 설명을 안보고 대략 이렇겠지 하고 짐작하고 했더니 생각했던거랑 달랐네요 ㅎㅎ
다음부터는 제대로 읽고 쓰겠습니다,,,

2024-07-17 11:05 UTC, alstn113 commented on backend/src/main/java/develup/submission/SubmissionService.java
> +        return SubmissionResponse.of(newSubmission);
저도 보통은 return 위를 개행하는 편입니다.

2024-07-17 11:06 UTC, alstn113 commented on backend/src/main/java/develup/submission/SubmissionService.java
> +@Transactional
서비스 종류에 따라 다른 것 같은데 맨 위에 붙은다는 것만 동일하면 상관없습니다.

2024-07-18 00:29 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/SubmissionApi.java
> +    public ResponseEntity<ApiResponse<SubmissionResponse>> postSubmission(@RequestBody CreateSubmissionRequest request) {
일단 유지하고 더 나은 네이밍이 생각나면 새로운 PR로 수정하겠습니다. 😆

2024-07-18 01:03 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/SubmissionService.java
> +@Transactional
저도 아톰과 같이 누락 방지를 위해 최상단에 `@Transactional`을 붙이는 것을 선호하는 편입니다! 😊
우선 유지하고 추후에 변경이 필요하면 변경하도록 하겠습니다.

2024-07-18 01:03 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/SubmissionService.java
> +        return SubmissionResponse.of(newSubmission);
그럼 이 부분은 반영하겠습니다!

2024-07-18 01:05 UTC, merged

2024-07-18 01:46 UTC, Parkhanyoung commented
훈훈하네요