디스커션/솔루션 당 부모 댓글 개수 조회하도록 수정 (issue #587)
woowacourse-teams/2024-devel-up pull request #591
Opened 2024-10-02 18:15 UTC by robinjoon

#### 구현 요약

사용자가 솔루션, 디스커션에 작성한 댓글 조회 시 댓글 개수 잘못 조회하는 오류 수정

댓글 개수는 부모 댓글 개수를 보여줍니다.

#### 연관 이슈

- close #587

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-10-03 04:15 UTC, le2sky requested changes
로빈 안녕하세요. 아톰입니다.
복잡한 작업이었을텐데, 잘해주셨네요. 몇 가지 코멘트 남겨놨습니다.
확인 부탁 드립니다. 🙇🏻‍♂️

2024-10-03 04:15 UTC, le2sky commented on backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentRepository.java
>              WHERE dc.member.id = :memberId AND dc.deletedAt is null
[Approve]

is null -> IS NULL 어떨까요?

2024-10-03 04:15 UTC, le2sky commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
>          List<MyDiscussionComment> mySolutionComments = discussionCommentRepository.findAllMyDiscussionComment(memberId);
[Commnet]

다른 곳은 댓글 count map(XXCommentCount) 조회하기 이전에 findAll로 타겟 객체 불러오는데, 이곳은 counts를 먼저 불러오네용

2024-10-03 09:50 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
>          List<MyDiscussionComment> mySolutionComments = discussionCommentRepository.findAllMyDiscussionComment(memberId);
반영했습니다. https://github.com/woowacourse-teams/2024-devel-up/pull/591/commits/ab5aac9974e5078a35d93b85d805cf56c9e38773

2024-10-03 09:50 UTC, robinjoon commented on backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentRepository.java
>              WHERE dc.member.id = :memberId AND dc.deletedAt is null
반영했습니다. https://github.com/woowacourse-teams/2024-devel-up/pull/591/commits/82a6769dc6195198f11caab992bec237008c090a

2024-10-03 09:50 UTC, robinjoon commented on backend/src/main/java/develup/application/solution/comment/SolutionCommentReadService.java
>          List<MySolutionComment> mySolutionComments = solutionCommentRepository.findAllMySolutionComment(memberId);
반영했습니다. https://github.com/woowacourse-teams/2024-devel-up/pull/591/commits/1755d3eb9366ba1bac03227ce9e1716a8dc21eb1

2024-10-03 09:51 UTC, robinjoon commented on backend/src/main/java/develup/application/solution/comment/SolutionCommentReadService.java
> +        return MySolutionCommentResponse.of(mySolutionComment, commentCount);
반영했습니다. https://github.com/woowacourse-teams/2024-devel-up/pull/591/commits/9f090bd7f7e26f5a4de276371bcbb534d434897e

2024-10-03 09:51 UTC, robinjoon commented on backend/src/main/java/develup/domain/solution/SolutionRepository.java
> +            ON sc.solution.id = s.id
반영했습니다. https://github.com/woowacourse-teams/2024-devel-up/pull/591/commits/ab6cf5813f9ea50768719a0aa49f0a9486c8c44e

2024-10-03 09:52 UTC, robinjoon commented on backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
> +    private static MyDiscussionCommentResponse mapToMyDiscussionCommentResponse(
반영했습니다. https://github.com/woowacourse-teams/2024-devel-up/pull/591/commits/ac306d1fe49d7af150d1c6b7b3e5b74d5593ed65

static 붙을 수 있으면 붙이는거 같은데, 기본 설정 바꾸는 법 아시나요? 전부터 불편해서 찾을때마다 안나와서 못하는중..

2024-10-04 01:58 UTC, Minjoo522 requested changes
로빈 안녕하세요.
필요한 코멘트는 대부분 아톰이 남겨주었네요!
그리고 별 거 아니긴한데 [chore: static 키우드 삭제](https://github.com/woowacourse-teams/2024-devel-up/pull/591/commits/ac306d1fe49d7af150d1c6b7b3e5b74d5593ed65 "chore: static 키우드 삭제") 커밋 메시지 오타 났네여. 혹시나 신경 쓰이시면 수정하시면 될 것 같습니다!

2024-10-04 01:58 UTC, Minjoo522 commented on backend/src/main/java/develup/domain/solution/comment/SolutionCommentCounts.java
> +    }
[Request Changes]

사용하지 않는 메서드는 지금 굳이 만들어둘 필요 없다고 생각합니다! 나중에 필요할 때 만들면 될 것 같아요~

2024-10-04 02:16 UTC, robinjoon commented on backend/src/main/java/develup/domain/solution/comment/SolutionCommentCounts.java
> +    }
`DiscussionCommentCounts` 복붙하다가 이렇게 되었네요. 수정했습니다! https://github.com/woowacourse-teams/2024-devel-up/pull/591/commits/fbe5320be11fa7a905c34b0e0acad48d2c180bbb

2024-10-04 04:14 UTC, alstn113 commented on backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentCounts.java
> +    }
[Comment]

하나만 사용해도 괜찮을 것 같아요!

2024-10-04 04:21 UTC, le2sky approved these changes
고생 많으셨습니다. 👍

2024-10-04 04:59 UTC, Minjoo522 approved these changes

2024-10-04 05:59 UTC, merged