lombok 적용 (issue #583)
woowacourse-teams/2024-devel-up pull request #594
Opened 2024-10-03 11:52 UTC by lilychoibb

#### 구현 요약

롬복 적용을 해보았어요!
코드가 엄청나게 줄어들었어요
제가 빠트린 설정이 있다면 말씀 부탁드려요 🤗

#### 연관 이슈

- close #583 

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-10-03 14:42 UTC, robinjoon requested changes
릴리 롬복 처음 사용해본다했는데 수고하셨어요! 코멘트 반영하고 다시 요청주세요~~

2024-10-03 14:42 UTC, robinjoon commented on backend/src/main/java/develup/domain/IdentifiableEntity.java
> +@NoArgsConstructor
[Request Change]

생성자의 접근 지정자를 기존처럼 protected로 해야 할 것 같아요~😀 다른 부분도 마찬가지루요

2024-10-03 14:42 UTC, robinjoon commented on backend/src/main/java/develup/domain/IdentifiableEntity.java
>      }
[Request Change]

AllArgsConstructor 사용하면 좋을 것 같아요~😀

2024-10-03 15:32 UTC, alstn113 requested changes
수고하셨습니다~

생성자로 `@Autowired`하는 부분 `@RequiredArgsConstructor` 부탁드립니다!

2024-10-04 01:20 UTC, lilychoibb commented on backend/src/main/java/develup/domain/IdentifiableEntity.java
> +@NoArgsConstructor
지정해줄 수 있는 지 몰랐네요😅 수정했습니다!

2024-10-04 01:28 UTC, Minjoo522 requested changes
안녕하세요, 릴리~
고생 많았습니다!
슬랙에 올린 것처럼 롬복은 편리한만큼 주의할 사항도 많은 것 같아요 😅
저번 회의 때 `@Data` 같은 건 사용하지 않기로 정한 것처럼 이렇게 정한 걸 사용금지 설정 해놓으면 컴파일 오류가 나서 개발자들이 실수하지 않을 수 있을 것 같아요!
(생각해보니 다시 어떤 규칙을 적용할지는 같이 논의해보는게 좋겠네요! 😊)
우선 관련 참고 자료들 링크 남기니 참고해주세요! 👍

- [Lombok 사용상 주의점(Pitfall)](https://kwonnam.pe.kr/wiki/java/lombok/pitfall#lombok_%EC%82%AC%EC%9A%A9%EC%83%81_%EC%A3%BC%EC%9D%98%EC%A0%90_pitfall)
- [Configuration system](https://projectlombok.org/features/configuration)

2024-10-04 02:20 UTC, robinjoon approved these changes
릴리 수고하셨습니다! 테스트 문제 없으니 이대로 가도 좋을 것 같아요. 혹시나 추후에 롬복을 사용할 수 있는데 안 한 부분이 발견되면 그때 그 부분 유동적으로 수정하면 될 것 같네요~

2024-10-04 02:41 UTC, le2sky requested changes
릴리 고생 많으셨어요. 👍
LogginFilter에 ObjectMapper 주입 받는 부분 확인 부탁드려요.
그리고 `@Slf4j` 어노테이션도 있는데 선택적으로 반영해주세요.

2024-10-04 04:29 UTC, lilychoibb commented
@le2sky 반영했습니다 :)

2024-10-04 05:04 UTC, Minjoo522 approved these changes

2024-10-04 05:04 UTC, alstn113 approved these changes
수고하셨습니다. ⛅️👍

2024-10-04 05:04 UTC, le2sky approved these changes
고생하셨습니다. 👍

2024-10-04 05:04 UTC, merged