리뷰 매칭 기능 구현(issue#33)
woowacourse-teams/2024-devel-up pull request #63
Opened 2024-07-18 08:28 UTC by le2sky

#### 구현 요약

이 부분을 제거하고 작업한 내용에 대해서 자유롭게 작성해주세요.

#### 연관 이슈

이 부분을 제거하고 연관된 이슈를 아래와 같이 명시해 닫아주세요.

> ex) close #12

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                  | 설명                             |
|---------------------|--------------------------------|
| R (Request Changes) | 적극적으로 반영을 고려해주세요               |
| C (Comment)         | 웬만하면 반영해주세요                    |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-07-18 10:51 UTC, lilychoibb commented on backend/src/test/java/develup/submission/PairServiceTest.java
> +                .hasMessage("매칭할 제출이 존재하지 않습니다.");
[Request Changes]
매칭할 제출이 존재하지 않을 때의 예외 메시지와 같은 것 같아요
의도하신 것인지 궁금합니다!
매칭할 제출은 있는데, 자신의 제출이라 매칭될 수 없으니 메시지를 다르게 해야할까 싶어서요 :)

2024-07-18 10:53 UTC, lilychoibb commented on backend/src/test/java/develup/submission/PairTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
[Request Changes]
여기는 hasMessage 가 없는 것 같아요!

2024-07-18 10:55 UTC, lilychoibb commented on backend/src/test/java/develup/submission/SubmissionTest.java
> +class SubmissionTest {
[Comment]
이 클래스도 createMember 등과 같이 메서드 분리를 하면 어떨까요?

2024-07-18 11:32 UTC, alstn113 approved these changes

2024-07-18 13:04 UTC, le2sky commented on backend/src/test/java/develup/submission/PairServiceTest.java
> +                .hasMessage("매칭할 제출이 존재하지 않습니다.");
꼼꼼하게 봐주셔서 감사합니다. 🙇🏻‍♂️
요구사항을 분석했을 때, 매칭의 대상은 "사용자가 소유한 제출들을 제외한 대기 중인 제출"이라고 생각했어요.
사용자 소유의 제출들을 제외한 나머지 매칭 대기 제출들이 존재하지 않는 상황이기 때문에 같은 예외 메시지를 사용했습니다!
바꾸는 것이 좋을까요!?

2024-07-18 13:15 UTC, le2sky commented on backend/src/test/java/develup/submission/PairTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
반영했습니다. 👍👍

2024-07-18 13:19 UTC, le2sky commented on backend/src/test/java/develup/submission/SubmissionTest.java
> +class SubmissionTest {
반영했습니다!

2024-07-18 15:26 UTC, robinjoon requested changes
CI CD 작업 수행하느라 이게 첫 기능 구현 리뷰네요... 그래서 그동안 논의를 따라가지 못한 부분이 있는 것 같아서, 질문 위주로 코멘트 남겼습니다! 이번 PR에 포함되지 않은 많은 부분에서도 제가 그 배경을 모르는 부분이 많을 것 같아요.. 물론 다들 잘 작성하셨을 것이라 믿지만, 논의된 내용이 무엇이고, 결정된 것이 무엇인지 알려줄 수 있는 시간이 있었으면 하네요.

2024-07-18 15:26 UTC, robinjoon commented on backend/src/main/java/develup/submission/SubmissionService.java
>      }
[Approve]

서비스 내부에서 다른 서비스를 참조하는 것에 대해 어떻게 생각하나요?
서비스 사이에 이런 의존성이 생긴다면 결국 서비스 레이어에서 암시적인 레이어가 생기게 되는데, 암시적인 만큼 눈에 보이지 않아서 조금 불편하다는 생각입니다.

2024-07-18 15:26 UTC, robinjoon commented on backend/src/test/java/develup/submission/PairServiceTest.java
> +                .hasMessage("매칭할 제출이 존재하지 않습니다.");
[Approve]
저 역시 서로 다른 예외 상황을 구분하기 힘들 수 있다는 점에서 예외 메세지가 동일한 것은 좋지 않다고 생각합니다. 다만, 아직 공통의 예외 처리 방식을 확정하지 않은 상태라고 생각해서 우선은 남겨둬도 괜찮을 것 같아 Approve로 남깁니다.

2024-07-18 23:24 UTC, le2sky commented on backend/src/test/java/develup/submission/PairServiceTest.java
> +                .hasMessage("매칭할 제출이 존재하지 않습니다.");
같은 예외 상황이라고 판단했기 때문에 같은 예외 메시지를 내려줬어요.
두 분이나 짚어주셨으니 이 코드가 명확하지 않은 코드일 수 있겠다 생각했어요.
우선, 지금 상황에서 가장 빠르게 논의되어야 하는 부분은 로빈이 말씀 주신 예외 처리 방식이니, 당장은 반영하지 않도록 할게요!

2024-07-18 23:44 UTC, Minjoo522 approved these changes
아톰, 길지 않은 시간 내에 기술 구현과 conflict 처리까지 하느라 고생하셨습니다!
꼭 변경해야 할 만한 사항은 보이지 않아 Approve 드립니다. 😊

2024-07-18 23:44 UTC, Minjoo522 commented on backend/src/test/java/develup/submission/PairServiceTest.java
> +        return memberRepository.save(member);
[Comment]

다른 패키지에서도 사용되는 것으로 보여서 따로 클래스로 분리해서 사용하는 건 어떻게 생각하시나요?

2024-07-18 23:44 UTC, Minjoo522 commented on backend/src/test/java/develup/submission/SubmissionServiceTest.java
> +            Member member = new Member(1L, "email", Provider.GITHUB, 1234L, "name", "image");
[Comment]

상단에서 선언하신 createMember 메서드를 사용해도 될 것 같습니다!

2024-07-18 23:52 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/PairStatus.java
> +}
대신 답변 드립니다.
`WAITING`은 `pair` 테이블의 `status`에 저장되는 값이 아닙니다.

로빈이 알고있는 바와 같이 `매칭이 되지 않으면 매칭이 존재하지 않는` 설계는 유지했습니다.
하지만 현재 진행 목록이나 특정 유저의 진행 중인 미션 조회에서 페어 매칭이 되지 않은 경우 `매칭 대기 상태`임을 클라이언트에게 전달해야만 하기 때문에 `WAITING`이 필요합니다.

아래 `submission` 패키지의 `MyMission`과 `SubmissionService` 클래스의 메서드와 API 응답 명세를 참고해주세요.

```java
// 📁 SubmissionService
    public List<MyMissionResponse> getMyMissions(Member member) {
        List<Submission> submissions = submissionRepository.findAllByMember_IdOrderByIdDesc(member.getId());

        return submissions.stream()
                .map(this::findMyMission)
                .map(MyMissionResponse::from)
                .toList();
    }

    private MyMission findMyMission(Submission submission) {
        return pairRepository.findMyMissionBySubmission(submission)
                .orElseGet(() -> MyMission.waitPairMatching(submission));
    }

// 📁 MyMission
    public static MyMission waitPairMatching(Submission submission) {
        return new MyMission(submission.getId(), submission.getMission(), submission.getUrl(), null, PairStatus.WAITING);
    }
```

```json
{
  "data": [
    {
      "id": 5,
      "mission": {
        "id": 3,
        "title": "숫자 추리 게임",
        "language": "JAVA",
        "description": "https://raw.githubusercontent.com/develup-mission/java-guessing-number/main/README.md",
        "thumbnail": "https://private-user-images.githubusercontent.com/80797824/348618796-753cae7d-779e-4847-b1b5-31ab9ff2d1cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDA3NTIsIm5iZiI6MTcyMTA0MDQ1MiwicGF0aCI6Ii84MDc5NzgyNC8zNDg2MTg3OTYtNzUzY2FlN2QtNzc5ZS00ODQ3LWIxYjUtMzFhYjlmZjJkMWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEwNDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ODM0ZjI2YWMxMGEzNGUzNDk2MjVlMTdlMWRkNjI4NjkyMWUxMTQzZDdhZjRlYjM2NTgzNjE0MTQ0YTZlZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yk09dRTA7LefjF0uTyYNkCgBRJcLizoKSJ8Otq7J1Gs",
        "url": "https://github.com/develup-mission/java-guessing-number"
      },
      "myPrLink": "https://github.com/develup-mission/java-guessing-number/pull/1",
      "pairPrLink": null,
      "status": "매칭 대기"
    },
    // ...
  ]
}
```

2024-07-18 23:56 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/MyMission.java
> +        return new MyMission(submission.getId(), submission.getMission(), submission.getUrl(), null, PairStatus.WAITING);
이전에 API 명세 작성 시 의논한 바 있는 것으로 기억합니다.
하기 참고 부탁 드려요! 😊

```json
{
	data : [{
	  id : 1,
    mission : {
			  "id": 1,
	      "title": "루터회관 흡연 단속",
	      "language": "JAVA",
	      "description": "루터회관 흡연 벌칙 프로그램을 구현한다.",
	      "thumbnail": "https://private-user-images.githubusercontent.com/39932141/348613012-a3adf64b-978d-4278-b5c1-6bc7c062d001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDA2ODMsIm5iZiI6MTcyMTA0MDM4MywicGF0aCI6Ii8zOTkzMjE0MS8zNDg2MTMwMTItYTNhZGY2NGItOTc4ZC00Mjc4LWI1YzEtNmJjN2MwNjJkMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEwNDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTZiOTY5NGIyNDI3Y2EyZDI3NzcwMjA2YzIzMGYwMzVkZGM4NGZjZjM2YTIyNjFjMmRkNzUzNWM4YjViOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xYP4xvx-GLne_6gRuSoejEPjTr9JD9U8xQq1r5WVq4U",
	      "url": "https://github.com/develup-mission/java-smoking"
		},
    myPrLink : "https://github.com/develup-mission/java-smoking/pull/1",
    pairPrLink : "https://github.com/develup-mission/java-smoking/pull/2",(status가 대기면 null)
    status : string(리뷰 완료, 리뷰 진행, 매칭 대기)
	},
	//...
	]
}
```

2024-07-19 00:45 UTC, le2sky commented on backend/src/main/java/develup/submission/MyMission.java
> +        return new MyMission(submission.getId(), submission.getMission(), submission.getUrl(), null, PairStatus.WAITING);
오오 리브 알려주셔서 감사해요. 
기억하기로는 논의하다가 흐지부지 됐던걸로 기억해요.
제가 놓치고 있는 것이 있을까요?

2024-07-19 00:53 UTC, Minjoo522 commented on backend/src/main/java/develup/submission/MyMission.java
> +        return new MyMission(submission.getId(), submission.getMission(), submission.getUrl(), null, PairStatus.WAITING);
그 이후는 저도 명확히 기억이 나진 않네요. 😅
클라이언트와 논의가 필요하긴 하겠지만 status가 매칭 대기인 경우 클라이언트 측에서 아예 pair pr로 이동하는 버튼을 보여주지 않아야합니다.
(즉, 분기 처리가 필수적입니다.)
만약 빈 문자열로 보내게되면 클라이언트 측에서 if (status === "") 이런식으로 비교하게 되는데 이것 보다는 if (status === null)이 더 명확하지 않을까 싶습니다.

2024-07-19 01:14 UTC, lilychoibb commented on backend/src/main/java/develup/submission/MyMission.java
> +        return new MyMission(submission.getId(), submission.getMission(), submission.getUrl(), null, PairStatus.WAITING);
저는 null 을 최대한 지양하자는 입장인데 (null 을 다루게 될 경우 고려해야 할 부분이 많아져서), null 과 빈 문자열을 혼용해서 쓰게 될 경우와 저희가 미리 논의했던 부분을 생각하면 당장은 반영하지 않아도 될 것 같아요 ㅎㅎ
이거는 추후에 가볍게 다시 한번 얘기 나눠봐도 좋을 것 같네요!

2024-07-19 01:16 UTC, lilychoibb approved these changes

2024-07-19 01:33 UTC, le2sky commented on backend/src/main/java/develup/submission/PairService.java
> +    }
`findCanMatchSubmission` 메서드에서 optional을 반환하는 이유는 말씀주신 이유처럼 null 처리를 위임하기 위해서입니다.
`canMatch` 메서드와 `matchWithOtherSubmission` 메서드에서 매칭할 수 있는 대상이 없는 경우 처리 방식이 다릅니다.
제가 놓치고 있는 부분이 있으면 추가 피드백 부탁드립니다. 🙇🏻‍♂️

2024-07-19 01:37 UTC, le2sky commented on backend/src/main/java/develup/submission/PairService.java
> +        pairRepository.save(otherPair);
Pair 쪽 데이터에서 submission1과 submission2로 나누기로 결정했었는데요.
이러한 구조는 자신의 submission을 식별하기 어렵다는 문제를 느꼈어요.
데이터 중복이 생기기는 하지만, 자신의 submission을 찾기 쉽게하기 위해서 Pair 데이터를 나눠서 저장하기로 논의했었어요.
이 부분에 대해서 사전에 미리 공유했어야 했는데, 죄송합니다. 🥲

2024-07-19 01:38 UTC, le2sky commented on backend/src/main/java/develup/submission/SubmissionService.java
>      }
제가 많이 부족하여 로빈의 피드백을 온전히 이해하기 어려워요.
암시적인 레이어가 무엇인지와 눈에 보이지 않아서 어떤 부분이 편하지 않는지에 대해서 더욱 의견을 듣고 반영해보고 싶어요.

2024-07-19 01:38 UTC, alstn113 commented on backend/src/main/java/develup/member/Member.java
깃허브에서 주는 고유한 값이라서 socialId를 넣었습니다. 

> 깃허브 유저 정보의 id값을 socialId에 넣었습니다.

로그인 시 socialId와 provider를 통해서 유저를 찾습니다. 😃

<details>
<summary>깃허브 유저 정보 참고</summary>
<img width="703" alt="image" src="https://github.com/user-attachments/assets/ea88bd1b-810a-4216-9b04-f35d48dc78ac">
</details>

2024-07-19 01:40 UTC, le2sky commented on backend/src/main/java/develup/submission/SubmissionService.java
> +        }
👍👍 반영했습니다.

2024-07-19 01:49 UTC, le2sky commented on backend/src/test/java/develup/submission/SubmissionServiceTest.java
> +            Member member = new Member(1L, "email", Provider.GITHUB, 1234L, "name", "image");
우선 inner 클래스 내부 메서드로 추출했어요. 👍
테스트 중복 코드 개선 PR에서 더욱 정밀하게 개선해볼까합니다!
의견 있으시면 자유롭게 공유 부탁드립니다.

2024-07-19 01:50 UTC, le2sky commented on backend/src/test/java/develup/submission/PairServiceTest.java
> +        return memberRepository.save(member);
마찬가지로 테스트 중복 코드 개선 PR에서 다뤄보려고 합니다.
우선 해당 PR에서는 반영하지 않도록 할게요!

2024-07-19 01:56 UTC, le2sky commented on backend/src/main/java/develup/submission/PairService.java
> +    }
좋은 의견 제안해주셔서 감사해요. 🙇🏻‍♂️
우선 해당 PR이 조금 루즈해져서 이 부분에 대해서 반영할지 고민이 되네요.
지금 당장 반영이 필요하다면 개선하구 아니라면 다른 PR에서 다뤄볼게요.
항상 같이 있으니 언제든지 자유롭게 말씀주세요.

2024-07-19 02:34 UTC, robinjoon approved these changes

2024-07-19 02:56 UTC, merged