Swagger 초기 설정 (issue #81)
woowacourse-teams/2024-devel-up pull request #86
Opened 2024-07-21 03:30 UTC by alstn113

#### 구현 요약

두괄식 결론

- Swagger 커스텀 어노테이션 없이 초기 설정만 했습니다.
- ⚠️ 커스텀 어노테이션 설정을 위해서는 우선 커스텀 예외와 전역 예외 처리에 대해서 정하고 가야할 것 같습니다.
- 개인적으로 응답 예시, 헤더, 필요하다면 파라미터 예시 등등이 들어간다고 생각하면 api document interface를 만들고 controller가 구현하는 방식이 좋을 것 같습니다.

추가적인 내용

- 프로젝트에서 정의한 ApiResponse record와 Swagger의 ApiResponse가 겹쳐서 좀 그럼
- Swagger 접속은 "{서버주소}/api-docs" or "{서버주소}/swagger-ui.html"로 접속 가능
- 버저닝은 고민이 됩니다. 

팀원 페이먼츠 미션 참고

- [릴리 미션 설정](https://github.dev/Minjoo522/spring-roomescape-payment/tree/step2)
  - Tag와 Operation의 summary만 사용했음.
- [리브 미션 설정](https://github.dev/Minjoo522/spring-roomescape-payment/tree/step2)
  - 성공과 예외에 대한 커스텀 어노테이션이 있으나, 예외 메세지가 보여지지 않고 타입만 나옴
  - ex) { message: string }
- [로빈 미션 설정](https://github.dev/robinjoon/spring-roomescape-payment/tree/step2%2C4)
  - 성공과 예외에 대한 커스텀 어노테이션을 작성했음.
  - 성공 커스텀이 필요한지 모르겠고, header에 대한 속성도 필요할 것 같음. 추후에 추가적인 속성이 더 들어갈 가능성도 있음.
  - 예외 커스텀에 대해서 예외 상태 코드와 메세지를 enum으로 정의했기 때문에 사용할 수 있었음. 아직 커스텀 예외에 대해서 정하지 않았지만 사용한다면 좋을 것 같음.
    - ex) `@ErrorApiResponse({DUPLICATE_RESERVATION_TIME, EMPTY_TIME})`

#### 연관 이슈

close #81

#### 참고

코드 리뷰에 `RCA 룰`을 적용할 시 참고해주세요.

| 헤더                | 설명                                                 |
| ------------------- | ---------------------------------------------------- |
| R (Request Changes) | 적극적으로 반영을 고려해주세요                       |
| C (Comment)         | 웬만하면 반영해주세요                                |
| A (Approve)         | 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다. |

2024-07-21 03:35 UTC, alstn113 commented on backend/src/main/resources/application.yml
> +
필요한 부분에 대해 간단한 설명입니다.

```yaml
springdoc:
  swagger-ui:
    path: /api-docs # 이 부분은 접속 경로입니다. "{서버주소}/api-docs"로 이동하면 "{서버주소}/swagger-docs/index.html"로 리다이렉트합니다.
    disable-swagger-default-url: true # pet store 예시 페이지 비활성화입니다.
    display-request-duration: true # 요청 시간 표시입니다.
```

2024-07-21 03:36 UTC, Minjoo522 requested changes
안녕하세요, 구름!
주말에도 Swagger 초기 설정하느라 고생했어요! 👍
버저닝과 커스텀 어노테이션은 백엔드 회의 때 다같이 논의해보면 좋을 것 같습니다.
초기 설정 해주신 것에 변경이 필요한 부분은 없는 것으로 보입니다!

다만 `.idea` 패키지가 같이 커밋되어서 확인 부탁합니다. 😊

2024-07-21 04:38 UTC, le2sky commented
구름 안녕하세요 아톰입니다.
제가 오늘 약속이 있어 내일 오전 이전까지 확인할게요 👍

2024-07-21 08:38 UTC, lilychoibb approved these changes
안녕하세요 구름 :) 
주말에 고생 많으셨어요! 
깔끔하게 초기 설정 해주셨네요 👍
고민되는 부분은 캠퍼스에서 마저 이야기해보아요!

2024-07-21 12:39 UTC, robinjoon approved these changes
레벨 2에서 커스텀 어노테이션과 이에 대한 해석기를 만들어서 사용했었는데요, 당시 예외 처리를 enum으로 구분해서 가능했던 방식이었습니다. 그리고 덕분에 문서는 깔끔하게 만들 수 있었어요. 저도 인터페이스로 문서를 정의하는 방식이 그리 나쁘기만 한 선택은 아니라고 생각해요. 하지만 이런 구조의 추가는 시스템의 복잡도를 높이기 때문에 신중하긴 해야 할 것 같아요. 월요일에 같이 고민해보시죠!

2024-07-21 23:14 UTC, le2sky approved these changes
구름 안녕하세요. 늦어서 죄송합니다.
잘 작성해주셔서 크게 드릴 말이 없었어요.
사소한 코멘트 하나 남겼는데, 자유롭게 반영해주세요 : )
고생하셨습니다. 👍

2024-07-21 23:14 UTC, le2sky commented on backend/build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
[Approve]

이 부분에 명시된 버전도 ext 변수로 관리할 수 있을까요??

2024-07-22 10:40 UTC, merged

2024-07-22 10:41 UTC, Minjoo522 approved these changes